/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.21
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON

#include "Python.h"

/*************************************************************** -*- c -*-
 * python/precommon.swg
 *
 * Rename all exported symbols from common.swg, to avoid symbol
 * clashes if multiple interpreters are included
 *
 ************************************************************************/

#define SWIG_TypeRegister    SWIG_Python_TypeRegister
#define SWIG_TypeCheck       SWIG_Python_TypeCheck
#define SWIG_TypeCast        SWIG_Python_TypeCast
#define SWIG_TypeDynamicCast SWIG_Python_TypeDynamicCast
#define SWIG_TypeName        SWIG_Python_TypeName
#define SWIG_TypeQuery       SWIG_Python_TypeQuery
#define SWIG_TypeClientData  SWIG_Python_TypeClientData
#define SWIG_PackData        SWIG_Python_PackData 
#define SWIG_UnpackData      SWIG_Python_UnpackData 


/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#  if defined(_MSC_VER) || defined(__GNUC__)
#    if defined(STATIC_LINKED)
#      define SWIGEXPORT(a) a
#      define SWIGIMPORT(a) extern a
#    else
#      define SWIGEXPORT(a) __declspec(dllexport) a
#      define SWIGIMPORT(a) extern a
#    endif
#  else
#    if defined(__BORLANDC__)
#      define SWIGEXPORT(a) a _export
#      define SWIGIMPORT(a) a _export
#    else
#      define SWIGEXPORT(a) a
#      define SWIGIMPORT(a) a
#    endif
#  endif
#else
#  define SWIGEXPORT(a) a
#  define SWIGIMPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#  define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#  define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;
  swig_converter_func     converter;
  const char             *str;
  void                   *clientdata;
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGIMPORT(void *)           SWIG_TypeCast(swig_type_info *, void *);
SWIGIMPORT(swig_type_info *) SWIG_TypeDynamicCast(swig_type_info *, void **);
SWIGIMPORT(const char *)     SWIG_TypeName(const swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGIMPORT(void)             SWIG_TypeClientData(swig_type_info *, void *);
SWIGIMPORT(char *)           SWIG_PackData(char *, void *, int);
SWIGIMPORT(char *)           SWIG_UnpackData(char *, void *, int);

#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti) {
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      if (tc->clientdata) ti->clientdata = tc->clientdata;
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
  l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  if (next) next->prev = head;
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty) {
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
        s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/* Cast a pointer up an inheritance hierarchy */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) {
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Dynamic pointer casting. Down an inheritance hierarchy */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/* Return the name associated with this type */
SWIGRUNTIME(const char *)
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata == clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = swig_type_list;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0))
          SWIG_TypeClientData(tc,clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

/* Pack binary data into a string */
SWIGRUNTIME(char *)
SWIG_PackData(char *c, void *ptr, int sz) {
  static char hex[17] = "0123456789abcdef";
  int i;
  unsigned char *u = (unsigned char *) ptr;
  register unsigned char uu;
  for (i = 0; i < sz; i++,u++) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
SWIGRUNTIME(char *)
SWIG_UnpackData(char *c, void *ptr, int sz) {
  register unsigned char uu = 0;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  int i;
  for (i = 0; i < sz; i++, u++) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

#endif

#ifdef __cplusplus
}
#endif

/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4
#define SWIG_PY_BINARY  5

/* Flags for pointer conversion */

#define SWIG_POINTER_EXCEPTION     0x1
#define SWIG_POINTER_DISOWN        0x2

/* Exception handling in wrappers */
#define SWIG_fail   goto fail

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

/* Common SWIG API */
#define SWIG_ConvertPtr(obj, pp, type, flags) \
  SWIG_Python_ConvertPtr(obj, pp, type, flags)
#define SWIG_NewPointerObj(p, type, flags) \
  SWIG_Python_NewPointerObj(p, type, flags)
#define SWIG_MustGetPtr(p, type, argnum, flags) \
  SWIG_Python_MustGetPtr(p, type, argnum, flags)

/* Python-specific SWIG API */
#define SWIG_newvarlink() \
  SWIG_Python_newvarlink()
#define SWIG_addvarlink(p, name, get_attr, set_attr) \
  SWIG_Python_addvarlink(p, name, get_attr, set_attr)
#define SWIG_ConvertPacked(obj, ptr, sz, ty, flags) \
  SWIG_Python_ConvertPacked(obj, ptr, sz, ty, flags)
#define SWIG_NewPackedObj(ptr, sz, type) \
  SWIG_Python_NewPackedObj(ptr, sz, type)
#define SWIG_InstallConstants(d, constants) \
  SWIG_Python_InstallConstants(d, constants)

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(int)               SWIG_Python_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGIMPORT(PyObject *)        SWIG_Python_NewPointerObj(void *, swig_type_info *,int own);
SWIGIMPORT(void *)            SWIG_Python_MustGetPtr(PyObject *, swig_type_info *, int, int);
SWIGIMPORT(PyObject *)        SWIG_Python_newvarlink(void);
SWIGIMPORT(void)              SWIG_Python_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGIMPORT(int)               SWIG_Python_ConvertPacked(PyObject *, void *, int sz, swig_type_info *, int);
SWIGIMPORT(PyObject *)        SWIG_Python_NewPackedObj(void *, int sz, swig_type_info *);
SWIGIMPORT(void)              SWIG_Python_InstallConstants(PyObject *d, swig_const_info constants[]);

#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  (char *)"swigvarlink",              /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_Python_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_Python_addvarlink(PyObject *p, char *name, PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_Python_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c = 0;
  static PyObject *SWIG_this = 0;
  int    newref = 0;
  PyObject  *pyobj = 0;

  if (!obj) return 0;
  if (obj == Py_None) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  }  
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) { Py_DECREF(obj); }
      return 0;
    } else {
      if (newref) { Py_DECREF(obj); }
      goto type_error;
    }
  }
  c++;
  c = SWIG_UnpackData(c,ptr,sizeof(void *));
  if (newref) { Py_DECREF(obj); }
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*) *ptr);
  }

  if ((pyobj) && (flags & SWIG_POINTER_DISOWN)) {
    PyObject *zero = PyInt_FromLong(0);
    PyObject_SetAttrString(pyobj,(char*)"thisown",zero);
    Py_DECREF(zero);
  }
  return 0;

type_error:
  if (flags & SWIG_POINTER_EXCEPTION) {
    if (ty && c) {
      char *temp = (char *) malloc(64+strlen(ty->name)+strlen(c));
      sprintf(temp,"Type error. Got %s, expected %s", c, ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Convert a pointer value, signal an exception on a type mismatch */
SWIGRUNTIME(void *)
SWIG_Python_MustGetPtr(PyObject *obj, swig_type_info *ty, int argnum, int flags) {
  void *result;
  SWIG_Python_ConvertPtr(obj, &result, ty, flags | SWIG_POINTER_EXCEPTION);
  return result;
}

/* Convert a packed value value */
SWIGRUNTIME(int)
SWIG_Python_ConvertPacked(PyObject *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c = 0;

  if ((!obj) || (!PyString_Check(obj))) goto type_error;
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
  }
  return 0;

type_error:

  if (flags) {
    if (ty && c) {
      char *temp = (char *) malloc(64+strlen(ty->name)+strlen(c));
      sprintf(temp,"Type error. Got %s, expected %s", c, ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_Python_NewPointerObj(void *ptr, swig_type_info *type, int own) {
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, (char *) type->name, NULL);
#else
  {
    char result[1024];
    char *r = result;
    *(r++) = '_';
    r = SWIG_PackData(r,&ptr,sizeof(void *));
    strcpy(r,type->name);
    robj = PyString_FromString(result);
  }
#endif
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyObject *inst;
    PyObject *args = Py_BuildValue((char*)"(O)", robj);
    Py_DECREF(robj);
    inst = PyObject_CallObject((PyObject *) type->clientdata, args);
    Py_DECREF(args);
    if (inst) {
      if (own) {
        PyObject *n = PyInt_FromLong(1);
        PyObject_SetAttrString(inst,(char*)"thisown",n);
        Py_DECREF(n);
      }
      robj = inst;
    }
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_Python_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  return PyString_FromString(result);
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_Python_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype,0);
      break;
    case SWIG_PY_BINARY:
      obj = SWIG_NewPackedObj(constants[i].pvalue, constants[i].lvalue, *(constants[i].ptype));
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

/* Contract support */

#define SWIG_contract_assert(expr, msg) if (!(expr)) { PyErr_SetString(PyExc_RuntimeError, (char *) msg ); goto fail; } else

#ifdef __cplusplus
}
#endif


/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_p_svm_node swig_types[0] 
#define  SWIGTYPE_p_svm_node swig_types[1] 
#define  SWIGTYPE_p_svm_parameter swig_types[2] 
#define  SWIGTYPE_p_double swig_types[3] 
#define  SWIGTYPE_p_svm_model swig_types[4] 
#define  SWIGTYPE_p_int swig_types[5] 
#define  SWIGTYPE_p_svm_problem swig_types[6] 
static swig_type_info *swig_types[8];

/* -------- TYPES TABLE (END) -------- */

#define SWIG_init    initsvmc

#define SWIG_name    "svmc"

#include "svm.h"


static int *new_int(int nelements) { 
  return (int *) calloc(nelements,sizeof(int)); 
}

static void delete_int(int *ary) { 
  free(ary); 
}

static int int_getitem(int *ary, int index) {
    return ary[index];
}
static void int_setitem(int *ary, int index, int value) {
    ary[index] = value;
}


static double *new_double(int nelements) { 
  return (double *) calloc(nelements,sizeof(double)); 
}

static void delete_double(double *ary) { 
  free(ary); 
}

static double double_getitem(double *ary, int index) {
    return ary[index];
}
static void double_setitem(double *ary, int index, double value) {
    ary[index] = value;
}


struct svm_node *svm_node_array(int size)
{
	return (struct svm_node *)malloc(sizeof(struct svm_node)*size);
}

void svm_node_array_set(struct svm_node *array, int i, int index, double value)
{
	array[i].index = index;
	array[i].value = value;
}

void svm_node_array_destroy(struct svm_node *array)
{
	free(array);
}

struct svm_node **svm_node_matrix(int size)
{
	return (struct svm_node **)malloc(sizeof(struct svm_node *)*size);	
}

void svm_node_matrix_set(struct svm_node **matrix, int i, struct svm_node* array)
{
	matrix[i] = array;
}

void svm_node_matrix_destroy(struct svm_node **matrix)
{
	free(matrix);
}


#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_svm_parameter_svm_type_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    int arg2 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:svm_parameter_svm_type_set",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1) (arg1)->svm_type = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_svm_type_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_parameter_svm_type_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int) ((arg1)->svm_type);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_kernel_type_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    int arg2 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:svm_parameter_kernel_type_set",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1) (arg1)->kernel_type = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_kernel_type_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_parameter_kernel_type_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int) ((arg1)->kernel_type);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_degree_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    double arg2 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Od:svm_parameter_degree_set",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1) (arg1)->degree = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_degree_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    double result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_parameter_degree_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double) ((arg1)->degree);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_gamma_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    double arg2 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Od:svm_parameter_gamma_set",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1) (arg1)->gamma = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_gamma_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    double result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_parameter_gamma_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double) ((arg1)->gamma);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_coef0_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    double arg2 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Od:svm_parameter_coef0_set",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1) (arg1)->coef0 = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_coef0_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    double result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_parameter_coef0_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double) ((arg1)->coef0);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_cache_size_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    double arg2 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Od:svm_parameter_cache_size_set",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1) (arg1)->cache_size = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_cache_size_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    double result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_parameter_cache_size_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double) ((arg1)->cache_size);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_eps_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    double arg2 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Od:svm_parameter_eps_set",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1) (arg1)->eps = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_eps_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    double result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_parameter_eps_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double) ((arg1)->eps);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_C_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    double arg2 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Od:svm_parameter_C_set",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1) (arg1)->C = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_C_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    double result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_parameter_C_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double) ((arg1)->C);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_nr_weight_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    int arg2 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:svm_parameter_nr_weight_set",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1) (arg1)->nr_weight = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_nr_weight_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_parameter_nr_weight_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int) ((arg1)->nr_weight);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_weight_label_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    int *arg2 = (int *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:svm_parameter_weight_label_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_int,SWIG_POINTER_EXCEPTION | SWIG_POINTER_DISOWN )) == -1) SWIG_fail;
    if (arg1) (arg1)->weight_label = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_weight_label_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    int *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_parameter_weight_label_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int *) ((arg1)->weight_label);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_int, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_weight_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    double *arg2 = (double *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:svm_parameter_weight_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_double,SWIG_POINTER_EXCEPTION | SWIG_POINTER_DISOWN )) == -1) SWIG_fail;
    if (arg1) (arg1)->weight = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_weight_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    double *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_parameter_weight_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double *) ((arg1)->weight);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_double, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_nu_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    double arg2 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Od:svm_parameter_nu_set",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1) (arg1)->nu = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_nu_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    double result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_parameter_nu_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double) ((arg1)->nu);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_p_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    double arg2 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Od:svm_parameter_p_set",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1) (arg1)->p = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_p_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    double result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_parameter_p_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double) ((arg1)->p);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_shrinking_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    int arg2 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:svm_parameter_shrinking_set",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1) (arg1)->shrinking = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_shrinking_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_parameter_shrinking_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int) ((arg1)->shrinking);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_probability_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    int arg2 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:svm_parameter_probability_set",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1) (arg1)->probability = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_parameter_probability_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_parameter_probability_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int) ((arg1)->probability);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_svm_parameter(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_svm_parameter")) goto fail;
    result = (struct svm_parameter *)(struct svm_parameter *) calloc(1, sizeof(struct svm_parameter));
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_svm_parameter, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_delete_svm_parameter(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_parameter *arg1 = (struct svm_parameter *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_svm_parameter",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    free((char *) arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_problem_l_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_problem *arg1 = (struct svm_problem *) 0 ;
    int arg2 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:svm_problem_l_set",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_problem,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1) (arg1)->l = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_problem_l_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_problem *arg1 = (struct svm_problem *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_problem_l_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_problem,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int) ((arg1)->l);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_problem_y_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_problem *arg1 = (struct svm_problem *) 0 ;
    double *arg2 = (double *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:svm_problem_y_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_problem,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_double,SWIG_POINTER_EXCEPTION | SWIG_POINTER_DISOWN )) == -1) SWIG_fail;
    if (arg1) (arg1)->y = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_problem_y_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_problem *arg1 = (struct svm_problem *) 0 ;
    double *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_problem_y_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_problem,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double *) ((arg1)->y);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_double, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_problem_x_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_problem *arg1 = (struct svm_problem *) 0 ;
    struct svm_node **arg2 = (struct svm_node **) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:svm_problem_x_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_problem,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_p_svm_node,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1) (arg1)->x = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_problem_x_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_problem *arg1 = (struct svm_problem *) 0 ;
    struct svm_node **result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_problem_x_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_problem,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (struct svm_node **) ((arg1)->x);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_p_svm_node, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_svm_problem(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_problem *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_svm_problem")) goto fail;
    result = (struct svm_problem *)(struct svm_problem *) calloc(1, sizeof(struct svm_problem));
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_svm_problem, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_delete_svm_problem(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_problem *arg1 = (struct svm_problem *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_svm_problem",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_problem,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    free((char *) arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_train(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_problem *arg1 = (struct svm_problem *) 0 ;
    struct svm_parameter *arg2 = (struct svm_parameter *) 0 ;
    struct svm_model *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:svm_train",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_problem,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (struct svm_model *)svm_train((struct svm_problem const *)arg1,(struct svm_parameter const *)arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_svm_model, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_cross_validation(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_problem *arg1 = (struct svm_problem *) 0 ;
    struct svm_parameter *arg2 = (struct svm_parameter *) 0 ;
    int arg3 ;
    double *arg4 = (double *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj3 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOiO:svm_cross_validation",&obj0,&obj1,&arg3,&obj3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_problem,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj3,(void **) &arg4, SWIGTYPE_p_double,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    svm_cross_validation((struct svm_problem const *)arg1,(struct svm_parameter const *)arg2,arg3,arg4);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_save_model(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    struct svm_model *arg2 = (struct svm_model *) 0 ;
    int result;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"sO:svm_save_model",&arg1,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_svm_model,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)svm_save_model((char const *)arg1,(struct svm_model const *)arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_load_model(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    struct svm_model *result;
    
    if(!PyArg_ParseTuple(args,(char *)"s:svm_load_model",&arg1)) goto fail;
    result = (struct svm_model *)svm_load_model((char const *)arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_svm_model, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_get_svm_type(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_model *arg1 = (struct svm_model *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_get_svm_type",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_model,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)svm_get_svm_type((struct svm_model const *)arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_get_nr_class(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_model *arg1 = (struct svm_model *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_get_nr_class",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_model,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)svm_get_nr_class((struct svm_model const *)arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_get_labels(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_model *arg1 = (struct svm_model *) 0 ;
    int *arg2 = (int *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:svm_get_labels",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_model,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_int,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    svm_get_labels((struct svm_model const *)arg1,arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_get_svr_probability(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_model *arg1 = (struct svm_model *) 0 ;
    double result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_get_svr_probability",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_model,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double)svm_get_svr_probability((struct svm_model const *)arg1);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_predict_values(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_model *arg1 = (struct svm_model *) 0 ;
    struct svm_node *arg2 = (struct svm_node *) 0 ;
    double *arg3 = (double *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:svm_predict_values",&obj0,&obj1,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_model,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_svm_node,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_double,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    svm_predict_values((struct svm_model const *)arg1,(struct svm_node const *)arg2,arg3);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_predict(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_model *arg1 = (struct svm_model *) 0 ;
    struct svm_node *arg2 = (struct svm_node *) 0 ;
    double result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:svm_predict",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_model,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_svm_node,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double)svm_predict((struct svm_model const *)arg1,(struct svm_node const *)arg2);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_predict_probability(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_model *arg1 = (struct svm_model *) 0 ;
    struct svm_node *arg2 = (struct svm_node *) 0 ;
    double *arg3 = (double *) 0 ;
    double result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:svm_predict_probability",&obj0,&obj1,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_model,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_svm_node,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_double,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double)svm_predict_probability((struct svm_model const *)arg1,(struct svm_node const *)arg2,arg3);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_destroy_model(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_model *arg1 = (struct svm_model *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_destroy_model",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_model,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    svm_destroy_model(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_check_parameter(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_problem *arg1 = (struct svm_problem *) 0 ;
    struct svm_parameter *arg2 = (struct svm_parameter *) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:svm_check_parameter",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_problem,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_svm_parameter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (char *)svm_check_parameter((struct svm_problem const *)arg1,(struct svm_parameter const *)arg2);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_check_probability_model(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_model *arg1 = (struct svm_model *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_check_probability_model",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_model,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)svm_check_probability_model((struct svm_model const *)arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_int(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    int *result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:new_int",&arg1)) goto fail;
    result = (int *)new_int(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_int, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_delete_int(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int *arg1 = (int *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_int",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_int,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    delete_int(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_int_getitem(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int *arg1 = (int *) 0 ;
    int arg2 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:int_getitem",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_int,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)int_getitem(arg1,arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_int_setitem(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int *arg1 = (int *) 0 ;
    int arg2 ;
    int arg3 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oii:int_setitem",&obj0,&arg2,&arg3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_int,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    int_setitem(arg1,arg2,arg3);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_double(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    double *result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:new_double",&arg1)) goto fail;
    result = (double *)new_double(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_double, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_delete_double(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    double *arg1 = (double *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_double",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_double,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    delete_double(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_double_getitem(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    double *arg1 = (double *) 0 ;
    int arg2 ;
    double result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:double_getitem",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_double,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double)double_getitem(arg1,arg2);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_double_setitem(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    double *arg1 = (double *) 0 ;
    int arg2 ;
    double arg3 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oid:double_setitem",&obj0,&arg2,&arg3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_double,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    double_setitem(arg1,arg2,arg3);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_node_array(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    struct svm_node *result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:svm_node_array",&arg1)) goto fail;
    result = (struct svm_node *)svm_node_array(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_svm_node, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_node_array_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_node *arg1 = (struct svm_node *) 0 ;
    int arg2 ;
    int arg3 ;
    double arg4 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oiid:svm_node_array_set",&obj0,&arg2,&arg3,&arg4)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_node,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    svm_node_array_set(arg1,arg2,arg3,arg4);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_node_array_destroy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_node *arg1 = (struct svm_node *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_node_array_destroy",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_svm_node,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    svm_node_array_destroy(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_node_matrix(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    struct svm_node **result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:svm_node_matrix",&arg1)) goto fail;
    result = (struct svm_node **)svm_node_matrix(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_p_svm_node, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_node_matrix_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_node **arg1 = (struct svm_node **) 0 ;
    int arg2 ;
    struct svm_node *arg3 = (struct svm_node *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OiO:svm_node_matrix_set",&obj0,&arg2,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_p_svm_node,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_svm_node,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    svm_node_matrix_set(arg1,arg2,arg3);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_svm_node_matrix_destroy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct svm_node **arg1 = (struct svm_node **) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:svm_node_matrix_destroy",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_p_svm_node,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    svm_node_matrix_destroy(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyMethodDef SwigMethods[] = {
	 { (char *)"svm_parameter_svm_type_set", _wrap_svm_parameter_svm_type_set, METH_VARARGS },
	 { (char *)"svm_parameter_svm_type_get", _wrap_svm_parameter_svm_type_get, METH_VARARGS },
	 { (char *)"svm_parameter_kernel_type_set", _wrap_svm_parameter_kernel_type_set, METH_VARARGS },
	 { (char *)"svm_parameter_kernel_type_get", _wrap_svm_parameter_kernel_type_get, METH_VARARGS },
	 { (char *)"svm_parameter_degree_set", _wrap_svm_parameter_degree_set, METH_VARARGS },
	 { (char *)"svm_parameter_degree_get", _wrap_svm_parameter_degree_get, METH_VARARGS },
	 { (char *)"svm_parameter_gamma_set", _wrap_svm_parameter_gamma_set, METH_VARARGS },
	 { (char *)"svm_parameter_gamma_get", _wrap_svm_parameter_gamma_get, METH_VARARGS },
	 { (char *)"svm_parameter_coef0_set", _wrap_svm_parameter_coef0_set, METH_VARARGS },
	 { (char *)"svm_parameter_coef0_get", _wrap_svm_parameter_coef0_get, METH_VARARGS },
	 { (char *)"svm_parameter_cache_size_set", _wrap_svm_parameter_cache_size_set, METH_VARARGS },
	 { (char *)"svm_parameter_cache_size_get", _wrap_svm_parameter_cache_size_get, METH_VARARGS },
	 { (char *)"svm_parameter_eps_set", _wrap_svm_parameter_eps_set, METH_VARARGS },
	 { (char *)"svm_parameter_eps_get", _wrap_svm_parameter_eps_get, METH_VARARGS },
	 { (char *)"svm_parameter_C_set", _wrap_svm_parameter_C_set, METH_VARARGS },
	 { (char *)"svm_parameter_C_get", _wrap_svm_parameter_C_get, METH_VARARGS },
	 { (char *)"svm_parameter_nr_weight_set", _wrap_svm_parameter_nr_weight_set, METH_VARARGS },
	 { (char *)"svm_parameter_nr_weight_get", _wrap_svm_parameter_nr_weight_get, METH_VARARGS },
	 { (char *)"svm_parameter_weight_label_set", _wrap_svm_parameter_weight_label_set, METH_VARARGS },
	 { (char *)"svm_parameter_weight_label_get", _wrap_svm_parameter_weight_label_get, METH_VARARGS },
	 { (char *)"svm_parameter_weight_set", _wrap_svm_parameter_weight_set, METH_VARARGS },
	 { (char *)"svm_parameter_weight_get", _wrap_svm_parameter_weight_get, METH_VARARGS },
	 { (char *)"svm_parameter_nu_set", _wrap_svm_parameter_nu_set, METH_VARARGS },
	 { (char *)"svm_parameter_nu_get", _wrap_svm_parameter_nu_get, METH_VARARGS },
	 { (char *)"svm_parameter_p_set", _wrap_svm_parameter_p_set, METH_VARARGS },
	 { (char *)"svm_parameter_p_get", _wrap_svm_parameter_p_get, METH_VARARGS },
	 { (char *)"svm_parameter_shrinking_set", _wrap_svm_parameter_shrinking_set, METH_VARARGS },
	 { (char *)"svm_parameter_shrinking_get", _wrap_svm_parameter_shrinking_get, METH_VARARGS },
	 { (char *)"svm_parameter_probability_set", _wrap_svm_parameter_probability_set, METH_VARARGS },
	 { (char *)"svm_parameter_probability_get", _wrap_svm_parameter_probability_get, METH_VARARGS },
	 { (char *)"new_svm_parameter", _wrap_new_svm_parameter, METH_VARARGS },
	 { (char *)"delete_svm_parameter", _wrap_delete_svm_parameter, METH_VARARGS },
	 { (char *)"svm_problem_l_set", _wrap_svm_problem_l_set, METH_VARARGS },
	 { (char *)"svm_problem_l_get", _wrap_svm_problem_l_get, METH_VARARGS },
	 { (char *)"svm_problem_y_set", _wrap_svm_problem_y_set, METH_VARARGS },
	 { (char *)"svm_problem_y_get", _wrap_svm_problem_y_get, METH_VARARGS },
	 { (char *)"svm_problem_x_set", _wrap_svm_problem_x_set, METH_VARARGS },
	 { (char *)"svm_problem_x_get", _wrap_svm_problem_x_get, METH_VARARGS },
	 { (char *)"new_svm_problem", _wrap_new_svm_problem, METH_VARARGS },
	 { (char *)"delete_svm_problem", _wrap_delete_svm_problem, METH_VARARGS },
	 { (char *)"svm_train", _wrap_svm_train, METH_VARARGS },
	 { (char *)"svm_cross_validation", _wrap_svm_cross_validation, METH_VARARGS },
	 { (char *)"svm_save_model", _wrap_svm_save_model, METH_VARARGS },
	 { (char *)"svm_load_model", _wrap_svm_load_model, METH_VARARGS },
	 { (char *)"svm_get_svm_type", _wrap_svm_get_svm_type, METH_VARARGS },
	 { (char *)"svm_get_nr_class", _wrap_svm_get_nr_class, METH_VARARGS },
	 { (char *)"svm_get_labels", _wrap_svm_get_labels, METH_VARARGS },
	 { (char *)"svm_get_svr_probability", _wrap_svm_get_svr_probability, METH_VARARGS },
	 { (char *)"svm_predict_values", _wrap_svm_predict_values, METH_VARARGS },
	 { (char *)"svm_predict", _wrap_svm_predict, METH_VARARGS },
	 { (char *)"svm_predict_probability", _wrap_svm_predict_probability, METH_VARARGS },
	 { (char *)"svm_destroy_model", _wrap_svm_destroy_model, METH_VARARGS },
	 { (char *)"svm_check_parameter", _wrap_svm_check_parameter, METH_VARARGS },
	 { (char *)"svm_check_probability_model", _wrap_svm_check_probability_model, METH_VARARGS },
	 { (char *)"new_int", _wrap_new_int, METH_VARARGS },
	 { (char *)"delete_int", _wrap_delete_int, METH_VARARGS },
	 { (char *)"int_getitem", _wrap_int_getitem, METH_VARARGS },
	 { (char *)"int_setitem", _wrap_int_setitem, METH_VARARGS },
	 { (char *)"new_double", _wrap_new_double, METH_VARARGS },
	 { (char *)"delete_double", _wrap_delete_double, METH_VARARGS },
	 { (char *)"double_getitem", _wrap_double_getitem, METH_VARARGS },
	 { (char *)"double_setitem", _wrap_double_setitem, METH_VARARGS },
	 { (char *)"svm_node_array", _wrap_svm_node_array, METH_VARARGS },
	 { (char *)"svm_node_array_set", _wrap_svm_node_array_set, METH_VARARGS },
	 { (char *)"svm_node_array_destroy", _wrap_svm_node_array_destroy, METH_VARARGS },
	 { (char *)"svm_node_matrix", _wrap_svm_node_matrix, METH_VARARGS },
	 { (char *)"svm_node_matrix_set", _wrap_svm_node_matrix_set, METH_VARARGS },
	 { (char *)"svm_node_matrix_destroy", _wrap_svm_node_matrix_destroy, METH_VARARGS },
	 { NULL, NULL }
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_p_svm_node[] = {{"_p_p_svm_node", 0, "struct svm_node **", 0},{"_p_p_svm_node"},{0}};
static swig_type_info _swigt__p_svm_node[] = {{"_p_svm_node", 0, "struct svm_node *", 0},{"_p_svm_node"},{0}};
static swig_type_info _swigt__p_svm_parameter[] = {{"_p_svm_parameter", 0, "struct svm_parameter *", 0},{"_p_svm_parameter"},{0}};
static swig_type_info _swigt__p_double[] = {{"_p_double", 0, "double *", 0},{"_p_double"},{0}};
static swig_type_info _swigt__p_svm_model[] = {{"_p_svm_model", 0, "struct svm_model *", 0},{"_p_svm_model"},{0}};
static swig_type_info _swigt__p_int[] = {{"_p_int", 0, "int *", 0},{"_p_int"},{0}};
static swig_type_info _swigt__p_svm_problem[] = {{"_p_svm_problem", 0, "struct svm_problem *", 0},{"_p_svm_problem"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_p_svm_node, 
_swigt__p_svm_node, 
_swigt__p_svm_parameter, 
_swigt__p_double, 
_swigt__p_svm_model, 
_swigt__p_int, 
_swigt__p_svm_problem, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
{ SWIG_PY_INT,     (char *)"C_SVC", (long) C_SVC, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"NU_SVC", (long) NU_SVC, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ONE_CLASS", (long) ONE_CLASS, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"EPSILON_SVR", (long) EPSILON_SVR, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"NU_SVR", (long) NU_SVR, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"LINEAR", (long) LINEAR, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"POLY", (long) POLY, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"RBF", (long) RBF, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"SIGMOID", (long) SIGMOID, 0, 0, 0},
{0}};

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) SWIG_init(void) {
    static PyObject *SWIG_globals = 0; 
    static int       typeinit = 0;
    PyObject *m, *d;
    int       i;
    if (!SWIG_globals) SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule((char *) SWIG_name, SwigMethods);
    d = PyModule_GetDict(m);
    
    if (!typeinit) {
        for (i = 0; swig_types_initial[i]; i++) {
            swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        }
        typeinit = 1;
    }
    SWIG_InstallConstants(d,swig_const_table);
    
}

