/*
 * FILE : svmc_wrap.c
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Patch 5)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : PYTHON */

#define SWIGPYTHON
#include <string.h>
#include <stdlib.h>
/***********************************************************************
 * $Header: /home/cvsroot/libsvm/python/svmc_wrap.c,v 1.1.1.1 2003-07-12 04:07:30 jo Exp $
 * swig_lib/python/python.cfg
 *
 * This file contains coded needed to add variable linking to the
 * Python interpreter.   C variables are added as a new kind of Python
 * datatype.
 *
 * Also contains supporting code for building python under Windows
 * and things like that.
 *
 * $Log: not supported by cvs2svn $
 ************************************************************************/

#ifdef __cplusplus
extern "C" {
#endif
#include "Python.h"
#ifdef __cplusplus
}
#endif

/* Definitions for Windows/Unix exporting */
#if defined(__WIN32__)
#   if defined(_MSC_VER)
#	define SWIGEXPORT(a,b) __declspec(dllexport) a b
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a,b) a _export b
#	else
#	    define SWIGEXPORT(a,b) a b
#	endif
#   endif
#else
#   define SWIGEXPORT(a,b) a b
#endif

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif

typedef struct {
  char  *name;
  PyObject *(*get_attr)(void);
  int (*set_attr)(PyObject *);
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar **vars;
  int      nvars;
  int      maxvars;
} swig_varlinkobject;

/* ----------------------------------------------------------------------
   swig_varlink_repr()

   Function for python repr method
   ---------------------------------------------------------------------- */

static PyObject *
swig_varlink_repr(swig_varlinkobject *v)
{
  v = v;
  return PyString_FromString("<Global variables>");
}

/* ---------------------------------------------------------------------
   swig_varlink_print()

   Print out all of the global variable names
   --------------------------------------------------------------------- */

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags)
{

  int i = 0;
  flags = flags;
  fprintf(fp,"Global variables { ");
  while (v->vars[i]) {
    fprintf(fp,"%s", v->vars[i]->name);
    i++;
    if (v->vars[i]) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

/* --------------------------------------------------------------------
   swig_varlink_getattr
 
   This function gets the value of a variable and returns it as a
   PyObject.   In our case, we'll be looking at the datatype and
   converting into a number or string
   -------------------------------------------------------------------- */

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n)
{
  int i = 0;
  char temp[128];

  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->get_attr)();
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return NULL;
}

/* -------------------------------------------------------------------
   swig_varlink_setattr()

   This function sets the value of a variable.
   ------------------------------------------------------------------- */

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p)
{
  char temp[128];
  int i = 0;
  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->set_attr)(p);
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return 1;
}

statichere PyTypeObject varlinktype = {
/*  PyObject_HEAD_INIT(&PyType_Type)  Note : This doesn't work on some machines */
  PyObject_HEAD_INIT(0)              
  0,
  "varlink",                          /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */

SWIGSTATIC PyObject *
SWIG_newvarlink(void)
{
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  /*  _Py_NewReference(result);  Does not seem to be necessary */
  result->nvars = 0;
  result->maxvars = 64;
  result->vars = (swig_globalvar **) malloc(64*sizeof(swig_globalvar *));
  result->vars[0] = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGSTATIC void
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p))
{
  swig_varlinkobject *v;
  v= (swig_varlinkobject *) p;
	
  if (v->nvars >= v->maxvars -1) {
    v->maxvars = 2*v->maxvars;
    v->vars = (swig_globalvar **) realloc(v->vars,v->maxvars*sizeof(swig_globalvar *));
    if (v->vars == NULL) {
      fprintf(stderr,"SWIG : Fatal error in initializing Python module.\n");
      exit(1);
    }
  }
  v->vars[v->nvars] = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  v->vars[v->nvars]->name = (char *) malloc(strlen(name)+1);
  strcpy(v->vars[v->nvars]->name,name);
  v->vars[v->nvars]->get_attr = get_attr;
  v->vars[v->nvars]->set_attr = set_attr;
  v->nvars++;
  v->vars[v->nvars] = 0;
}



/*****************************************************************************
 * $Header: /home/cvsroot/libsvm/python/svmc_wrap.c,v 1.1.1.1 2003-07-12 04:07:30 jo Exp $
 *
 * swigptr.swg
 *
 * This file contains supporting code for the SWIG run-time type checking
 * mechanism.  The following functions are available :
 *
 * SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *));
 *
 *      Registers a new type-mapping with the type-checker.  origtype is the
 *      original datatype and newtype is an equivalent type.  cast is optional
 *      pointer to a function to cast pointer values between types (this
 *      is typically used to cast pointers from derived classes to base classes in C++)
 *      
 * SWIG_MakePtr(char *buffer, void *ptr, char *typestring);
 *     
 *      Makes a pointer string from a pointer and typestring.  The result is returned
 *      in buffer which is assumed to hold enough space for the result.
 *
 * char * SWIG_GetPtr(char *buffer, void **ptr, char *type)
 *
 *      Gets a pointer value from a string.  If there is a type-mismatch, returns
 *      a character string to the received type.  On success, returns NULL.
 *
 *
 * You can remap these functions by making a file called "swigptr.swg" in
 * your the same directory as the interface file you are wrapping.
 *
 * These functions are normally declared static, but this file can be
 * can be used in a multi-module environment by redefining the symbol
 * SWIGSTATIC.
 *****************************************************************************/

#include <stdlib.h>

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif


/* SWIG pointer structure */

typedef struct SwigPtrType {
  char               *name;               /* Datatype name                  */
  int                 len;                /* Length (used for optimization) */
  void               *(*cast)(void *);    /* Pointer casting function       */
  struct SwigPtrType *next;               /* Linked list pointer            */
} SwigPtrType;

/* Pointer cache structure */

typedef struct {
  int                 stat;               /* Status (valid) bit             */
  SwigPtrType        *tp;                 /* Pointer to type structure      */
  char                name[256];          /* Given datatype name            */
  char                mapped[256];        /* Equivalent name                */
} SwigCacheType;

/* Some variables  */

static int SwigPtrMax  = 64;           /* Max entries that can be currently held */
                                       /* This value may be adjusted dynamically */
static int SwigPtrN    = 0;            /* Current number of entries              */
static int SwigPtrSort = 0;            /* Status flag indicating sort            */
static int SwigStart[256];             /* Starting positions of types            */

/* Pointer table */
static SwigPtrType *SwigPtrTable = 0;  /* Table containing pointer equivalences  */

/* Cached values */

#define SWIG_CACHESIZE  8
#define SWIG_CACHEMASK  0x7
static SwigCacheType SwigCache[SWIG_CACHESIZE];  
static int SwigCacheIndex = 0;
static int SwigLastCache = 0;

/* Sort comparison function */
static int swigsort(const void *data1, const void *data2) {
	SwigPtrType *d1 = (SwigPtrType *) data1;
	SwigPtrType *d2 = (SwigPtrType *) data2;
	return strcmp(d1->name,d2->name);
}

/* Binary Search function */
static int swigcmp(const void *key, const void *data) {
  char *k = (char *) key;
  SwigPtrType *d = (SwigPtrType *) data;
  return strncmp(k,d->name,d->len);
}

/* Register a new datatype with the type-checker */

SWIGSTATIC 
void SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *)) {

  int i;
  SwigPtrType *t = 0,*t1;

  /* Allocate the pointer table if necessary */

  if (!SwigPtrTable) {     
    SwigPtrTable = (SwigPtrType *) malloc(SwigPtrMax*sizeof(SwigPtrType));
    SwigPtrN = 0;
  }
  /* Grow the table */
  if (SwigPtrN >= SwigPtrMax) {
    SwigPtrMax = 2*SwigPtrMax;
    SwigPtrTable = (SwigPtrType *) realloc((char *) SwigPtrTable,SwigPtrMax*sizeof(SwigPtrType));
  }
  for (i = 0; i < SwigPtrN; i++)
    if (strcmp(SwigPtrTable[i].name,origtype) == 0) {
      t = &SwigPtrTable[i];
      break;
    }
  if (!t) {
    t = &SwigPtrTable[SwigPtrN];
    t->name = origtype;
    t->len = strlen(t->name);
    t->cast = 0;
    t->next = 0;
    SwigPtrN++;
  }

  /* Check for existing entry */

  while (t->next) {
    if ((strcmp(t->name,newtype) == 0)) {
      if (cast) t->cast = cast;
      return;
    }
    t = t->next;
  }
  
  /* Now place entry (in sorted order) */

  t1 = (SwigPtrType *) malloc(sizeof(SwigPtrType));
  t1->name = newtype;
  t1->len = strlen(t1->name);
  t1->cast = cast;
  t1->next = 0;            
  t->next = t1;           
  SwigPtrSort = 0;
}

/* Make a pointer value string */

SWIGSTATIC 
void SWIG_MakePtr(char *_c, const void *_ptr, char *type) {
  static char _hex[16] =
  {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
   'a', 'b', 'c', 'd', 'e', 'f'};
  unsigned long _p, _s;
  char _result[20], *_r;    /* Note : a 64-bit hex number = 16 digits */
  _r = _result;
  _p = (unsigned long) _ptr;
  if (_p > 0) {
    while (_p > 0) {
      _s = _p & 0xf;
      *(_r++) = _hex[_s];
      _p = _p >> 4;
    }
    *_r = '_';
    while (_r >= _result)
      *(_c++) = *(_r--);
  } else {
    strcpy (_c, "NULL");
  }
  if (_ptr)
    strcpy (_c, type);
}

/* Define for backwards compatibility */

#define _swig_make_hex   SWIG_MakePtr 

/* Function for getting a pointer value */

SWIGSTATIC 
char *SWIG_GetPtr(char *_c, void **ptr, char *_t)
{
  unsigned long _p;
  char temp_type[256];
  char *name;
  int  i, len;
  SwigPtrType *sp,*tp;
  SwigCacheType *cache;
  int  start, end;
  _p = 0;

  /* Pointer values must start with leading underscore */
  if (*_c == '_') {
      _c++;
      /* Extract hex value from pointer */
      while (*_c) {
	  if ((*_c >= '0') && (*_c <= '9'))
	    _p = (_p << 4) + (*_c - '0');
	  else if ((*_c >= 'a') && (*_c <= 'f'))
	    _p = (_p << 4) + ((*_c - 'a') + 10);
	  else
	    break;
	  _c++;
      }

      if (_t) {
	if (strcmp(_t,_c)) { 
	  if (!SwigPtrSort) {
	    qsort((void *) SwigPtrTable, SwigPtrN, sizeof(SwigPtrType), swigsort); 
	    for (i = 0; i < 256; i++) {
	      SwigStart[i] = SwigPtrN;
	    }
	    for (i = SwigPtrN-1; i >= 0; i--) {
	      SwigStart[(int) (SwigPtrTable[i].name[1])] = i;
	    }
	    for (i = 255; i >= 1; i--) {
	      if (SwigStart[i-1] > SwigStart[i])
		SwigStart[i-1] = SwigStart[i];
	    }
	    SwigPtrSort = 1;
	    for (i = 0; i < SWIG_CACHESIZE; i++)  
	      SwigCache[i].stat = 0;
	  }
	  
	  /* First check cache for matches.  Uses last cache value as starting point */
	  cache = &SwigCache[SwigLastCache];
	  for (i = 0; i < SWIG_CACHESIZE; i++) {
	    if (cache->stat) {
	      if (strcmp(_t,cache->name) == 0) {
		if (strcmp(_c,cache->mapped) == 0) {
		  cache->stat++;
		  *ptr = (void *) _p;
		  if (cache->tp->cast) *ptr = (*(cache->tp->cast))(*ptr);
		  return (char *) 0;
		}
	      }
	    }
	    SwigLastCache = (SwigLastCache+1) & SWIG_CACHEMASK;
	    if (!SwigLastCache) cache = SwigCache;
	    else cache++;
	  }
	  /* We have a type mismatch.  Will have to look through our type
	     mapping table to figure out whether or not we can accept this datatype */

	  start = SwigStart[(int) _t[1]];
	  end = SwigStart[(int) _t[1]+1];
	  sp = &SwigPtrTable[start];
	  while (start < end) {
	    if (swigcmp(_t,sp) == 0) break;
	    sp++;
	    start++;
	  }
	  if (start >= end) sp = 0;
	  /* Try to find a match for this */
	  if (sp) {
	    while (swigcmp(_t,sp) == 0) {
	      name = sp->name;
	      len = sp->len;
	      tp = sp->next;
	      /* Try to find entry for our given datatype */
	      while(tp) {
		if (tp->len >= 255) {
		  return _c;
		}
		strcpy(temp_type,tp->name);
		strncat(temp_type,_t+len,255-tp->len);
		if (strcmp(_c,temp_type) == 0) {
		  
		  strcpy(SwigCache[SwigCacheIndex].mapped,_c);
		  strcpy(SwigCache[SwigCacheIndex].name,_t);
		  SwigCache[SwigCacheIndex].stat = 1;
		  SwigCache[SwigCacheIndex].tp = tp;
		  SwigCacheIndex = SwigCacheIndex & SWIG_CACHEMASK;
		  
		  /* Get pointer value */
		  *ptr = (void *) _p;
		  if (tp->cast) *ptr = (*(tp->cast))(*ptr);
		  return (char *) 0;
		}
		tp = tp->next;
	      }
	      sp++;
	      /* Hmmm. Didn't find it this time */
	    }
	  }
	  /* Didn't find any sort of match for this data.  
	     Get the pointer value and return the received type */
	  *ptr = (void *) _p;
	  return _c;
	} else {
	  /* Found a match on the first try.  Return pointer value */
	  *ptr = (void *) _p;
	  return (char *) 0;
	}
      } else {
	/* No type specified.  Good luck */
	*ptr = (void *) _p;
	return (char *) 0;
      }
  } else {
    if (strcmp (_c, "NULL") == 0) {
	*ptr = (void *) 0;
	return (char *) 0;
    }
    *ptr = (void *) 0;	
    return _c;
  }
}

/* Compatibility mode */

#define _swig_get_hex  SWIG_GetPtr

#define SWIG_init    initsvmc

#define SWIG_name    "svmc"

#include "svm.h"

#define  SWIG_MemoryError    1
#define  SWIG_IOError        2
#define  SWIG_RuntimeError   3
#define  SWIG_IndexError     4
#define  SWIG_TypeError      5
#define  SWIG_DivisionByZero 6
#define  SWIG_OverflowError  7
#define  SWIG_SyntaxError    8
#define  SWIG_ValueError     9
#define  SWIG_SystemError   10
#define  SWIG_UnknownError  99

static void _SWIG_exception(int code, char *msg) {
  switch(code) {
  case SWIG_MemoryError:
    PyErr_SetString(PyExc_MemoryError,msg);
    break;
  case SWIG_IOError:
    PyErr_SetString(PyExc_IOError,msg);
    break;
  case SWIG_RuntimeError:
    PyErr_SetString(PyExc_RuntimeError,msg);
    break;
  case SWIG_IndexError:
    PyErr_SetString(PyExc_IndexError,msg);
    break;
  case SWIG_TypeError:
    PyErr_SetString(PyExc_TypeError,msg);
    break;
  case SWIG_DivisionByZero:
    PyErr_SetString(PyExc_ZeroDivisionError,msg);
    break;
  case SWIG_OverflowError:
    PyErr_SetString(PyExc_OverflowError,msg);
    break;
  case SWIG_SyntaxError:
    PyErr_SetString(PyExc_SyntaxError,msg);
    break;
  case SWIG_ValueError:
    PyErr_SetString(PyExc_ValueError,msg);
    break;
  case SWIG_SystemError:
    PyErr_SetString(PyExc_SystemError,msg);
    break;
  default:
    PyErr_SetString(PyExc_RuntimeError,msg);
    break;
  }
}

#define SWIG_exception(a,b) _SWIG_exception(a,b); return NULL

#include <limits.h>

/* Create a new integer array */

  static int *int_array(int size) {
#ifdef __cplusplus
    return new int[size];
#else
    return (int *) malloc(size*sizeof(int));
#endif
  }

  /* Destroy an integer array */

  static void int_destroy(int *array) {
    if (array) {
#ifdef __cplusplus
      delete array;
#else
      free(array);
#endif
    }
  }

  /* Return an element */

  static int int_get(int *array, int index) {
    if (array) {
      return array[index];
    } else {
      return INT_MIN;
    }
  }
   
  /* Set an element */
  
  static int int_set(int *array, int index, int value) {
    if (array) {
      return (array[index] = value);
    } else {
      return INT_MIN;
    }
  }


  #include <float.h>

  /* Create a new float array */

  static float *float_array(int size) {
#ifdef __cplusplus
    return new float[size];
#else
    return (float *) malloc(size*sizeof(float));
#endif
  }

  /* Destroy an array */

  static void float_destroy(float *array) {
    if (array) {
#ifdef __cplusplus
      delete array;
#else
      free(array);
#endif
    }
  }

  /* Return an element */

  static float float_get(float *array, int index) {
    if (array) {
      return array[index];
    } else {
      return FLT_MIN;
    }
  }
   
  /* Set an element */
  
  static float float_set(float *array, int index, float value) {
    if (array) {
      return (array[index] = value);
    } else {
      return FLT_MIN;
    }
  }

  /* Create a new double array */

  static double *double_array(int size) {
#ifdef __cplusplus
    return new double[size];
#else
    return (double *) malloc(size*sizeof(double));
#endif
  }

  /* Destroy an array */

  static void double_destroy(double *array) {
    if (array) {
#ifdef __cplusplus
      delete array;
#else
      free(array);
#endif
    }
  }

  /* Return an element */

  static double double_get(double *array, int index) {
    if (array) {
      return array[index];
    } else {
      return FLT_MIN;
    }
  }
   
  /* Set an element */
  
  static double double_set(double *array, int index, double value) {
    if (array) {
      return (array[index] = value);
    } else {
      return FLT_MIN;
    }
  }


/* Create character string arrays */

static char **string_array(int size) {
  char **a;
  int i;
#ifdef __cplusplus
  a = new char *[size];
#else
  a = (char **) malloc(size*sizeof(char *));
#endif
  for (i = 0; i < size; i++)
    a[i] = 0;
  return a;
}

/* Destroy a string array */

static void string_destroy(char **array) {
  int i = 0;
  if (array) {
      while (array[i]) {
#ifdef __cplusplus
            delete array[i];
#else
            free(array[i]);
#endif
            i++;
      }          	
#ifdef __cplusplus
     delete array;
#else
     free(array);
#endif
   }      
}

/* Get an element */

static char *string_get(char **array_string, int index) {
  if (array_string) 
    if (array_string[index]) return (array_string[index]);
    else return "";
  else 
    return "";
}

/* Set an element */

static char *string_set(char **array_string, int index, char * val) {
  if (array_string) {
    if (array_string[index]) {
#ifdef __cplusplus
	delete array_string[index];
#else
        free(array_string[index]);
#endif
    }	
    if (strlen(val) > 0) {
#ifdef __cplusplus
      array_string[index] = new char[strlen(val)+1];
#else
      array_string[index] = (char *) malloc(strlen(val)+1);
#endif
      strcpy(array_string[index],val);
      return array_string[index];
    } else {
      array_string[index] = 0;
      return val;
    }
  } else return val;
}


struct svm_node *svm_node_array(int size)
{
	return (struct svm_node *)malloc(sizeof(struct svm_node)*size);
}

void svm_node_array_set(struct svm_node *array, int i, int index, double value)
{
	array[i].index = index;
	array[i].value = value;
}

void svm_node_array_destroy(struct svm_node *array)
{
	free(array);
}

struct svm_node **svm_node_matrix(int size)
{
	return (struct svm_node **)malloc(sizeof(struct svm_node *)*size);	
}

void svm_node_matrix_set(struct svm_node **matrix, int i, struct svm_node* array)
{
	matrix[i] = array;
}

void svm_node_matrix_destroy(struct svm_node **matrix)
{
	free(matrix);
}

static PyObject *_wrap_svm_train(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_model * _result;
    struct svm_problem * _arg0;
    struct svm_parameter * _arg1;
    char * _argc0 = 0;
    char * _argc1 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"ss:svm_train",&_argc0,&_argc1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_problem_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_train. Expected _struct_svm_problem_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of svm_train. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (struct svm_model *)svm_train(_arg0,_arg1);
    SWIG_MakePtr(_ptemp, (char *) _result,"_struct_svm_model_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_svm_save_model(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    char * _arg0;
    struct svm_model * _arg1;
    char * _argc1 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"ss:svm_save_model",&_arg0,&_argc1)) 
        return NULL;
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_struct_svm_model_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of svm_save_model. Expected _struct_svm_model_p.");
        return NULL;
        }
    }
    _result = (int )svm_save_model(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_svm_load_model(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_model * _result;
    char * _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_load_model",&_arg0)) 
        return NULL;
    _result = (struct svm_model *)svm_load_model(_arg0);
    SWIG_MakePtr(_ptemp, (char *) _result,"_struct_svm_model_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_svm_predict(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_model * _arg0;
    struct svm_node * _arg1;
    char * _argc0 = 0;
    char * _argc1 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"ss:svm_predict",&_argc0,&_argc1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_model_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_predict. Expected _struct_svm_model_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_struct_svm_node_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of svm_predict. Expected _struct_svm_node_p.");
        return NULL;
        }
    }
    _result = (double )svm_predict(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

static PyObject *_wrap_svm_destroy_model(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_model * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_destroy_model",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_model_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_destroy_model. Expected _struct_svm_model_p.");
        return NULL;
        }
    }
    svm_destroy_model(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_svm_check_parameter(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char * _result;
    struct svm_problem * _arg0;
    struct svm_parameter * _arg1;
    char * _argc0 = 0;
    char * _argc1 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"ss:svm_check_parameter",&_argc0,&_argc1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_problem_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_check_parameter. Expected _struct_svm_problem_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of svm_check_parameter. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (char *)svm_check_parameter(_arg0,_arg1);
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

static PyObject *_wrap_int_array(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int * _result;
    int  _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"i:int_array",&_arg0)) 
        return NULL;
    _result = (int *)int_array(_arg0);
    SWIG_MakePtr(_ptemp, (char *) _result,"_int_p");
    _resultobj = Py_BuildValue("s",_ptemp);
{
  if (!_result) {
    SWIG_exception(SWIG_MemoryError,"Out of memory.");
  }
}
    return _resultobj;
}

static PyObject *_wrap_int_destroy(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:int_destroy",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_int_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of int_destroy. Expected _int_p.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    int_destroy(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_int_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    int * _arg0;
    int  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"si:int_get",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_int_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of int_get. Expected _int_p.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    _result = (int )int_get(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_int_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    int * _arg0;
    int  _arg1;
    int  _arg2;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sii:int_set",&_argc0,&_arg1,&_arg2)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_int_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of int_set. Expected _int_p.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    _result = (int )int_set(_arg0,_arg1,_arg2);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_double_array(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double * _result;
    int  _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"i:double_array",&_arg0)) 
        return NULL;
    _result = (double *)double_array(_arg0);
    SWIG_MakePtr(_ptemp, (char *) _result,"_double_p");
    _resultobj = Py_BuildValue("s",_ptemp);
{
  if (!_result) {
    SWIG_exception(SWIG_MemoryError,"Out of memory.");
  }
}
    return _resultobj;
}

static PyObject *_wrap_double_destroy(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:double_destroy",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of double_destroy. Expected _double_p.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    double_destroy(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_double_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    double * _arg0;
    int  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"si:double_get",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of double_get. Expected _double_p.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    _result = (double )double_get(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

static PyObject *_wrap_double_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    double * _arg0;
    int  _arg1;
    double  _arg2;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sid:double_set",&_argc0,&_arg1,&_arg2)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of double_set. Expected _double_p.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    _result = (double )double_set(_arg0,_arg1,_arg2);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

static PyObject *_wrap_float_array(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    float * _result;
    int  _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"i:float_array",&_arg0)) 
        return NULL;
    _result = (float *)float_array(_arg0);
    SWIG_MakePtr(_ptemp, (char *) _result,"_float_p");
    _resultobj = Py_BuildValue("s",_ptemp);
{
  if (!_result) {
    SWIG_exception(SWIG_MemoryError,"Out of memory.");
  }
}
    return _resultobj;
}

static PyObject *_wrap_float_destroy(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    float * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:float_destroy",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_float_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of float_destroy. Expected _float_p.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    float_destroy(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_float_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    float  _result;
    float * _arg0;
    int  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"si:float_get",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_float_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of float_get. Expected _float_p.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    _result = (float )float_get(_arg0,_arg1);
    _resultobj = Py_BuildValue("f",_result);
    return _resultobj;
}

static PyObject *_wrap_float_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    float  _result;
    float * _arg0;
    int  _arg1;
    float  _arg2;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sif:float_set",&_argc0,&_arg1,&_arg2)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_float_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of float_set. Expected _float_p.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    _result = (float )float_set(_arg0,_arg1,_arg2);
    _resultobj = Py_BuildValue("f",_result);
    return _resultobj;
}

static PyObject *_wrap_string_array(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char ** _result;
    int  _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"i:string_array",&_arg0)) 
        return NULL;
    _result = (char **)string_array(_arg0);
    SWIG_MakePtr(_ptemp, (char *) _result,"_char_pp");
    _resultobj = Py_BuildValue("s",_ptemp);
{
  if (!_result) {
    SWIG_exception(SWIG_MemoryError,"Out of memory.");
  }
}
    return _resultobj;
}

static PyObject *_wrap_string_destroy(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char ** _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:string_destroy",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_char_pp")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of string_destroy. Expected _char_pp.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    string_destroy(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_string_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char * _result;
    char ** _arg0;
    int  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"si:string_get",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_char_pp")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of string_get. Expected _char_pp.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    _result = (char *)string_get(_arg0,_arg1);
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

static PyObject *_wrap_string_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char * _result;
    char ** _arg0;
    int  _arg1;
    char * _arg2;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sis:string_set",&_argc0,&_arg1,&_arg2)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_char_pp")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of string_set. Expected _char_pp.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    _result = (char *)string_set(_arg0,_arg1,_arg2);
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

static PyObject *_wrap_svm_node_array(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_node * _result;
    int  _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"i:svm_node_array",&_arg0)) 
        return NULL;
    _result = (struct svm_node *)svm_node_array(_arg0);
    SWIG_MakePtr(_ptemp, (char *) _result,"_struct_svm_node_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_svm_node_array_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_node * _arg0;
    int  _arg1;
    int  _arg2;
    double  _arg3;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"siid:svm_node_array_set",&_argc0,&_arg1,&_arg2,&_arg3)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_node_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_node_array_set. Expected _struct_svm_node_p.");
        return NULL;
        }
    }
    svm_node_array_set(_arg0,_arg1,_arg2,_arg3);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_svm_node_array_destroy(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_node * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_node_array_destroy",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_node_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_node_array_destroy. Expected _struct_svm_node_p.");
        return NULL;
        }
    }
    svm_node_array_destroy(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_svm_node_matrix(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_node ** _result;
    int  _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"i:svm_node_matrix",&_arg0)) 
        return NULL;
    _result = (struct svm_node **)svm_node_matrix(_arg0);
    SWIG_MakePtr(_ptemp, (char *) _result,"_struct_svm_node_pp");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_svm_node_matrix_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_node ** _arg0;
    int  _arg1;
    struct svm_node * _arg2;
    char * _argc0 = 0;
    char * _argc2 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sis:svm_node_matrix_set",&_argc0,&_arg1,&_argc2)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_node_pp")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_node_matrix_set. Expected _struct_svm_node_pp.");
        return NULL;
        }
    }
    if (_argc2) {
        if (SWIG_GetPtr(_argc2,(void **) &_arg2,"_struct_svm_node_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 3 of svm_node_matrix_set. Expected _struct_svm_node_p.");
        return NULL;
        }
    }
    svm_node_matrix_set(_arg0,_arg1,_arg2);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_svm_node_matrix_destroy(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_node ** _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_node_matrix_destroy",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_node_pp")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_node_matrix_destroy. Expected _struct_svm_node_pp.");
        return NULL;
        }
    }
    svm_node_matrix_destroy(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define svm_parameter_svm_type_set(_swigobj,_swigval) (_swigobj->svm_type = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_svm_type_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_parameter * _arg0;
    int  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"si:svm_parameter_svm_type_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_svm_type_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (int )svm_parameter_svm_type_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define svm_parameter_svm_type_get(_swigobj) ((int ) _swigobj->svm_type)
static PyObject *_wrap_svm_parameter_svm_type_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_parameter * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_parameter_svm_type_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_svm_type_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (int )svm_parameter_svm_type_get(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define svm_parameter_kernel_type_set(_swigobj,_swigval) (_swigobj->kernel_type = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_kernel_type_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_parameter * _arg0;
    int  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"si:svm_parameter_kernel_type_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_kernel_type_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (int )svm_parameter_kernel_type_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define svm_parameter_kernel_type_get(_swigobj) ((int ) _swigobj->kernel_type)
static PyObject *_wrap_svm_parameter_kernel_type_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_parameter * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_parameter_kernel_type_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_kernel_type_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (int )svm_parameter_kernel_type_get(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define svm_parameter_degree_set(_swigobj,_swigval) (_swigobj->degree = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_degree_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    double  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sd:svm_parameter_degree_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_degree_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_degree_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_degree_get(_swigobj) ((double ) _swigobj->degree)
static PyObject *_wrap_svm_parameter_degree_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_parameter_degree_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_degree_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_degree_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_gamma_set(_swigobj,_swigval) (_swigobj->gamma = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_gamma_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    double  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sd:svm_parameter_gamma_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_gamma_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_gamma_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_gamma_get(_swigobj) ((double ) _swigobj->gamma)
static PyObject *_wrap_svm_parameter_gamma_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_parameter_gamma_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_gamma_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_gamma_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_coef0_set(_swigobj,_swigval) (_swigobj->coef0 = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_coef0_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    double  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sd:svm_parameter_coef0_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_coef0_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_coef0_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_coef0_get(_swigobj) ((double ) _swigobj->coef0)
static PyObject *_wrap_svm_parameter_coef0_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_parameter_coef0_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_coef0_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_coef0_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_cache_size_set(_swigobj,_swigval) (_swigobj->cache_size = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_cache_size_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    double  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sd:svm_parameter_cache_size_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_cache_size_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_cache_size_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_cache_size_get(_swigobj) ((double ) _swigobj->cache_size)
static PyObject *_wrap_svm_parameter_cache_size_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_parameter_cache_size_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_cache_size_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_cache_size_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_eps_set(_swigobj,_swigval) (_swigobj->eps = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_eps_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    double  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sd:svm_parameter_eps_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_eps_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_eps_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_eps_get(_swigobj) ((double ) _swigobj->eps)
static PyObject *_wrap_svm_parameter_eps_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_parameter_eps_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_eps_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_eps_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_C_set(_swigobj,_swigval) (_swigobj->C = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_C_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    double  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sd:svm_parameter_C_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_C_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_C_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_C_get(_swigobj) ((double ) _swigobj->C)
static PyObject *_wrap_svm_parameter_C_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_parameter_C_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_C_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_C_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_nr_weight_set(_swigobj,_swigval) (_swigobj->nr_weight = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_nr_weight_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_parameter * _arg0;
    int  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"si:svm_parameter_nr_weight_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_nr_weight_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (int )svm_parameter_nr_weight_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define svm_parameter_nr_weight_get(_swigobj) ((int ) _swigobj->nr_weight)
static PyObject *_wrap_svm_parameter_nr_weight_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_parameter * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_parameter_nr_weight_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_nr_weight_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (int )svm_parameter_nr_weight_get(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define svm_parameter_weight_label_set(_swigobj,_swigval) (_swigobj->weight_label = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_weight_label_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int * _result;
    struct svm_parameter * _arg0;
    int * _arg1;
    char * _argc0 = 0;
    char * _argc1 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"ss:svm_parameter_weight_label_set",&_argc0,&_argc1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_weight_label_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_int_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of svm_parameter_weight_label_set. Expected _int_p.");
        return NULL;
        }
    }
    _result = (int *)svm_parameter_weight_label_set(_arg0,_arg1);
    SWIG_MakePtr(_ptemp, (char *) _result,"_int_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

#define svm_parameter_weight_label_get(_swigobj) ((int *) _swigobj->weight_label)
static PyObject *_wrap_svm_parameter_weight_label_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int * _result;
    struct svm_parameter * _arg0;
    char * _argc0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_parameter_weight_label_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_weight_label_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (int *)svm_parameter_weight_label_get(_arg0);
    SWIG_MakePtr(_ptemp, (char *) _result,"_int_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

#define svm_parameter_weight_set(_swigobj,_swigval) (_swigobj->weight = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_weight_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double * _result;
    struct svm_parameter * _arg0;
    double * _arg1;
    char * _argc0 = 0;
    char * _argc1 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"ss:svm_parameter_weight_set",&_argc0,&_argc1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_weight_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of svm_parameter_weight_set. Expected _double_p.");
        return NULL;
        }
    }
    _result = (double *)svm_parameter_weight_set(_arg0,_arg1);
    SWIG_MakePtr(_ptemp, (char *) _result,"_double_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

#define svm_parameter_weight_get(_swigobj) ((double *) _swigobj->weight)
static PyObject *_wrap_svm_parameter_weight_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double * _result;
    struct svm_parameter * _arg0;
    char * _argc0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_parameter_weight_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_weight_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double *)svm_parameter_weight_get(_arg0);
    SWIG_MakePtr(_ptemp, (char *) _result,"_double_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

#define svm_parameter_nu_set(_swigobj,_swigval) (_swigobj->nu = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_nu_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    double  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sd:svm_parameter_nu_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_nu_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_nu_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_nu_get(_swigobj) ((double ) _swigobj->nu)
static PyObject *_wrap_svm_parameter_nu_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_parameter_nu_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_nu_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_nu_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_p_set(_swigobj,_swigval) (_swigobj->p = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_p_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    double  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sd:svm_parameter_p_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_p_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_p_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_p_get(_swigobj) ((double ) _swigobj->p)
static PyObject *_wrap_svm_parameter_p_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_parameter_p_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_p_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_p_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_shrinking_set(_swigobj,_swigval) (_swigobj->shrinking = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_shrinking_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_parameter * _arg0;
    int  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"si:svm_parameter_shrinking_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_shrinking_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (int )svm_parameter_shrinking_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define svm_parameter_shrinking_get(_swigobj) ((int ) _swigobj->shrinking)
static PyObject *_wrap_svm_parameter_shrinking_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_parameter * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_parameter_shrinking_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_shrinking_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (int )svm_parameter_shrinking_get(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define new_svm_parameter() ((struct svm_parameter *) calloc(1,sizeof(struct svm_parameter)))
static PyObject *_wrap_new_svm_parameter(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_parameter * _result;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,":new_svm_parameter")) 
        return NULL;
    _result = (struct svm_parameter *)new_svm_parameter();
    SWIG_MakePtr(_ptemp, (char *) _result,"_struct_svm_parameter_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

#define delete_svm_parameter(_swigobj) (free ((char *) _swigobj))
static PyObject *_wrap_delete_svm_parameter(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_parameter * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:delete_svm_parameter",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of delete_svm_parameter. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    delete_svm_parameter(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define svm_problem_l_set(_swigobj,_swigval) (_swigobj->l = _swigval,_swigval)
static PyObject *_wrap_svm_problem_l_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_problem * _arg0;
    int  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"si:svm_problem_l_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_problem_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_problem_l_set. Expected _struct_svm_problem_p.");
        return NULL;
        }
    }
    _result = (int )svm_problem_l_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define svm_problem_l_get(_swigobj) ((int ) _swigobj->l)
static PyObject *_wrap_svm_problem_l_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_problem * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_problem_l_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_problem_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_problem_l_get. Expected _struct_svm_problem_p.");
        return NULL;
        }
    }
    _result = (int )svm_problem_l_get(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define svm_problem_y_set(_swigobj,_swigval) (_swigobj->y = _swigval,_swigval)
static PyObject *_wrap_svm_problem_y_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double * _result;
    struct svm_problem * _arg0;
    double * _arg1;
    char * _argc0 = 0;
    char * _argc1 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"ss:svm_problem_y_set",&_argc0,&_argc1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_problem_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_problem_y_set. Expected _struct_svm_problem_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of svm_problem_y_set. Expected _double_p.");
        return NULL;
        }
    }
    _result = (double *)svm_problem_y_set(_arg0,_arg1);
    SWIG_MakePtr(_ptemp, (char *) _result,"_double_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

#define svm_problem_y_get(_swigobj) ((double *) _swigobj->y)
static PyObject *_wrap_svm_problem_y_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double * _result;
    struct svm_problem * _arg0;
    char * _argc0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_problem_y_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_problem_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_problem_y_get. Expected _struct_svm_problem_p.");
        return NULL;
        }
    }
    _result = (double *)svm_problem_y_get(_arg0);
    SWIG_MakePtr(_ptemp, (char *) _result,"_double_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

#define svm_problem_x_set(_swigobj,_swigval) (_swigobj->x = _swigval,_swigval)
static PyObject *_wrap_svm_problem_x_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_node ** _result;
    struct svm_problem * _arg0;
    struct svm_node ** _arg1;
    char * _argc0 = 0;
    char * _argc1 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"ss:svm_problem_x_set",&_argc0,&_argc1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_problem_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_problem_x_set. Expected _struct_svm_problem_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_struct_svm_node_pp")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of svm_problem_x_set. Expected _struct_svm_node_pp.");
        return NULL;
        }
    }
    _result = (struct svm_node **)svm_problem_x_set(_arg0,_arg1);
    SWIG_MakePtr(_ptemp, (char *) _result,"_struct_svm_node_pp");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

#define svm_problem_x_get(_swigobj) ((struct svm_node **) _swigobj->x)
static PyObject *_wrap_svm_problem_x_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_node ** _result;
    struct svm_problem * _arg0;
    char * _argc0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_problem_x_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_problem_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_problem_x_get. Expected _struct_svm_problem_p.");
        return NULL;
        }
    }
    _result = (struct svm_node **)svm_problem_x_get(_arg0);
    SWIG_MakePtr(_ptemp, (char *) _result,"_struct_svm_node_pp");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

#define new_svm_problem() ((struct svm_problem *) calloc(1,sizeof(struct svm_problem)))
static PyObject *_wrap_new_svm_problem(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_problem * _result;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,":new_svm_problem")) 
        return NULL;
    _result = (struct svm_problem *)new_svm_problem();
    SWIG_MakePtr(_ptemp, (char *) _result,"_struct_svm_problem_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

#define delete_svm_problem(_swigobj) (free ((char *) _swigobj))
static PyObject *_wrap_delete_svm_problem(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_problem * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:delete_svm_problem",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_struct_svm_problem_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of delete_svm_problem. Expected _struct_svm_problem_p.");
        return NULL;
        }
    }
    delete_svm_problem(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyMethodDef svmcMethods[] = {
	 { "delete_svm_problem", _wrap_delete_svm_problem, 1 },
	 { "new_svm_problem", _wrap_new_svm_problem, 1 },
	 { "svm_problem_x_get", _wrap_svm_problem_x_get, 1 },
	 { "svm_problem_x_set", _wrap_svm_problem_x_set, 1 },
	 { "svm_problem_y_get", _wrap_svm_problem_y_get, 1 },
	 { "svm_problem_y_set", _wrap_svm_problem_y_set, 1 },
	 { "svm_problem_l_get", _wrap_svm_problem_l_get, 1 },
	 { "svm_problem_l_set", _wrap_svm_problem_l_set, 1 },
	 { "delete_svm_parameter", _wrap_delete_svm_parameter, 1 },
	 { "new_svm_parameter", _wrap_new_svm_parameter, 1 },
	 { "svm_parameter_shrinking_get", _wrap_svm_parameter_shrinking_get, 1 },
	 { "svm_parameter_shrinking_set", _wrap_svm_parameter_shrinking_set, 1 },
	 { "svm_parameter_p_get", _wrap_svm_parameter_p_get, 1 },
	 { "svm_parameter_p_set", _wrap_svm_parameter_p_set, 1 },
	 { "svm_parameter_nu_get", _wrap_svm_parameter_nu_get, 1 },
	 { "svm_parameter_nu_set", _wrap_svm_parameter_nu_set, 1 },
	 { "svm_parameter_weight_get", _wrap_svm_parameter_weight_get, 1 },
	 { "svm_parameter_weight_set", _wrap_svm_parameter_weight_set, 1 },
	 { "svm_parameter_weight_label_get", _wrap_svm_parameter_weight_label_get, 1 },
	 { "svm_parameter_weight_label_set", _wrap_svm_parameter_weight_label_set, 1 },
	 { "svm_parameter_nr_weight_get", _wrap_svm_parameter_nr_weight_get, 1 },
	 { "svm_parameter_nr_weight_set", _wrap_svm_parameter_nr_weight_set, 1 },
	 { "svm_parameter_C_get", _wrap_svm_parameter_C_get, 1 },
	 { "svm_parameter_C_set", _wrap_svm_parameter_C_set, 1 },
	 { "svm_parameter_eps_get", _wrap_svm_parameter_eps_get, 1 },
	 { "svm_parameter_eps_set", _wrap_svm_parameter_eps_set, 1 },
	 { "svm_parameter_cache_size_get", _wrap_svm_parameter_cache_size_get, 1 },
	 { "svm_parameter_cache_size_set", _wrap_svm_parameter_cache_size_set, 1 },
	 { "svm_parameter_coef0_get", _wrap_svm_parameter_coef0_get, 1 },
	 { "svm_parameter_coef0_set", _wrap_svm_parameter_coef0_set, 1 },
	 { "svm_parameter_gamma_get", _wrap_svm_parameter_gamma_get, 1 },
	 { "svm_parameter_gamma_set", _wrap_svm_parameter_gamma_set, 1 },
	 { "svm_parameter_degree_get", _wrap_svm_parameter_degree_get, 1 },
	 { "svm_parameter_degree_set", _wrap_svm_parameter_degree_set, 1 },
	 { "svm_parameter_kernel_type_get", _wrap_svm_parameter_kernel_type_get, 1 },
	 { "svm_parameter_kernel_type_set", _wrap_svm_parameter_kernel_type_set, 1 },
	 { "svm_parameter_svm_type_get", _wrap_svm_parameter_svm_type_get, 1 },
	 { "svm_parameter_svm_type_set", _wrap_svm_parameter_svm_type_set, 1 },
	 { "svm_node_matrix_destroy", _wrap_svm_node_matrix_destroy, 1 },
	 { "svm_node_matrix_set", _wrap_svm_node_matrix_set, 1 },
	 { "svm_node_matrix", _wrap_svm_node_matrix, 1 },
	 { "svm_node_array_destroy", _wrap_svm_node_array_destroy, 1 },
	 { "svm_node_array_set", _wrap_svm_node_array_set, 1 },
	 { "svm_node_array", _wrap_svm_node_array, 1 },
	 { "string_set", _wrap_string_set, 1 },
	 { "string_get", _wrap_string_get, 1 },
	 { "string_destroy", _wrap_string_destroy, 1 },
	 { "string_array", _wrap_string_array, 1 },
	 { "float_set", _wrap_float_set, 1 },
	 { "float_get", _wrap_float_get, 1 },
	 { "float_destroy", _wrap_float_destroy, 1 },
	 { "float_array", _wrap_float_array, 1 },
	 { "double_set", _wrap_double_set, 1 },
	 { "double_get", _wrap_double_get, 1 },
	 { "double_destroy", _wrap_double_destroy, 1 },
	 { "double_array", _wrap_double_array, 1 },
	 { "int_set", _wrap_int_set, 1 },
	 { "int_get", _wrap_int_get, 1 },
	 { "int_destroy", _wrap_int_destroy, 1 },
	 { "int_array", _wrap_int_array, 1 },
	 { "svm_check_parameter", _wrap_svm_check_parameter, 1 },
	 { "svm_destroy_model", _wrap_svm_destroy_model, 1 },
	 { "svm_predict", _wrap_svm_predict, 1 },
	 { "svm_load_model", _wrap_svm_load_model, 1 },
	 { "svm_save_model", _wrap_svm_save_model, 1 },
	 { "svm_train", _wrap_svm_train, 1 },
	 { NULL, NULL }
};
static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT(void,initsvmc)() {
	 PyObject *m, *d;
	 SWIG_globals = SWIG_newvarlink();
	 m = Py_InitModule("svmc", svmcMethods);
	 d = PyModule_GetDict(m);
	 PyDict_SetItemString(d,"C_SVC", PyInt_FromLong((long) C_SVC));
	 PyDict_SetItemString(d,"NU_SVC", PyInt_FromLong((long) NU_SVC));
	 PyDict_SetItemString(d,"ONE_CLASS", PyInt_FromLong((long) ONE_CLASS));
	 PyDict_SetItemString(d,"EPSILON_SVR", PyInt_FromLong((long) EPSILON_SVR));
	 PyDict_SetItemString(d,"NU_SVR", PyInt_FromLong((long) NU_SVR));
	 PyDict_SetItemString(d,"LINEAR", PyInt_FromLong((long) LINEAR));
	 PyDict_SetItemString(d,"POLY", PyInt_FromLong((long) POLY));
	 PyDict_SetItemString(d,"RBF", PyInt_FromLong((long) RBF));
	 PyDict_SetItemString(d,"SIGMOID", PyInt_FromLong((long) SIGMOID));
/*
 * These are the pointer type-equivalency mappings. 
 * (Used by the SWIG pointer type-checker).
 */
	 SWIG_RegisterMapping("_signed_long","_long",0);
	 SWIG_RegisterMapping("_long","_unsigned_long",0);
	 SWIG_RegisterMapping("_long","_signed_long",0);
	 SWIG_RegisterMapping("_svm_problem","_struct_svm_problem",0);
	 SWIG_RegisterMapping("_unsigned_long","_long",0);
	 SWIG_RegisterMapping("_signed_int","_int",0);
	 SWIG_RegisterMapping("_svm_parameter","_struct_svm_parameter",0);
	 SWIG_RegisterMapping("_unsigned_short","_short",0);
	 SWIG_RegisterMapping("_signed_short","_short",0);
	 SWIG_RegisterMapping("_unsigned_int","_int",0);
	 SWIG_RegisterMapping("_short","_unsigned_short",0);
	 SWIG_RegisterMapping("_short","_signed_short",0);
	 SWIG_RegisterMapping("_int","_unsigned_int",0);
	 SWIG_RegisterMapping("_int","_signed_int",0);
	 SWIG_RegisterMapping("_struct_svm_problem","_svm_problem",0);
	 SWIG_RegisterMapping("_struct_svm_parameter","_svm_parameter",0);
}
