/*
 * FILE : svmc_wrap.c
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Build 883)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : PYTHON */

#define SWIGPYTHON
/***********************************************************************
 * $Header: /home/cvsroot/libsvm/python/svmc_wrap.c,v 1.2 2003-11-10 06:57:51 cjlin Exp $
 * swig_lib/python/python.cfg
 *
 * Contains variable linking and pointer type-checking code.
 ************************************************************************/

#include <string.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif
#include "Python.h"

/* Definitions for Windows/Unix exporting */
#if defined(_WIN32) || defined(__WIN32__)
#   if defined(_MSC_VER)
#	define SWIGEXPORT(a) __declspec(dllexport) a
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a) a _export
#	else
#	    define SWIGEXPORT(a) a
#	endif
#   endif
#else
#   define SWIGEXPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGSTATICRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGSTATICRUNTIME(a) static a
#endif

typedef struct {
  char  *name;
  PyObject *(*get_attr)(void);
  int (*set_attr)(PyObject *);
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar **vars;
  int      nvars;
  int      maxvars;
} swig_varlinkobject;

/* ----------------------------------------------------------------------
   swig_varlink_repr()

   Function for python repr method
   ---------------------------------------------------------------------- */

static PyObject *
swig_varlink_repr(swig_varlinkobject *v)
{
  v = v;
  return PyString_FromString("<Global variables>");
}

/* ---------------------------------------------------------------------
   swig_varlink_print()

   Print out all of the global variable names
   --------------------------------------------------------------------- */

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags)
{

  int i = 0;
  flags = flags;
  fprintf(fp,"Global variables { ");
  while (v->vars[i]) {
    fprintf(fp,"%s", v->vars[i]->name);
    i++;
    if (v->vars[i]) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

/* --------------------------------------------------------------------
   swig_varlink_getattr
 
   This function gets the value of a variable and returns it as a
   PyObject.   In our case, we'll be looking at the datatype and
   converting into a number or string
   -------------------------------------------------------------------- */

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n)
{
  int i = 0;
  char temp[128];

  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->get_attr)();
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return NULL;
}

/* -------------------------------------------------------------------
   swig_varlink_setattr()

   This function sets the value of a variable.
   ------------------------------------------------------------------- */

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p)
{
  char temp[128];
  int i = 0;
  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->set_attr)(p);
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return 1;
}

statichere PyTypeObject varlinktype = {
/*  PyObject_HEAD_INIT(&PyType_Type)  Note : This doesn't work on some machines */
  PyObject_HEAD_INIT(0)              
  0,
  "varlink",                          /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */

SWIGSTATICRUNTIME(PyObject *)
SWIG_newvarlink(void)
{
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  /*  _Py_NewReference(result);  Does not seem to be necessary */
  result->nvars = 0;
  result->maxvars = 64;
  result->vars = (swig_globalvar **) malloc(64*sizeof(swig_globalvar *));
  result->vars[0] = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGSTATICRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p))
{
  swig_varlinkobject *v;
  v= (swig_varlinkobject *) p;
	
  if (v->nvars >= v->maxvars -1) {
    v->maxvars = 2*v->maxvars;
    v->vars = (swig_globalvar **) realloc(v->vars,v->maxvars*sizeof(swig_globalvar *));
    if (v->vars == NULL) {
      fprintf(stderr,"SWIG : Fatal error in initializing Python module.\n");
      exit(1);
    }
  }
  v->vars[v->nvars] = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  v->vars[v->nvars]->name = (char *) malloc(strlen(name)+1);
  strcpy(v->vars[v->nvars]->name,name);
  v->vars[v->nvars]->get_attr = get_attr;
  v->vars[v->nvars]->set_attr = set_attr;
  v->nvars++;
  v->vars[v->nvars] = 0;
}

/* -----------------------------------------------------------------------------
 * Pointer type-checking
 * ----------------------------------------------------------------------------- */

/* SWIG pointer structure */
typedef struct SwigPtrType {
  char               *name;               /* Datatype name                  */
  int                 len;                /* Length (used for optimization) */
  void               *(*cast)(void *);    /* Pointer casting function       */
  struct SwigPtrType *next;               /* Linked list pointer            */
} SwigPtrType;

/* Pointer cache structure */
typedef struct {
  int                 stat;               /* Status (valid) bit             */
  SwigPtrType        *tp;                 /* Pointer to type structure      */
  char                name[256];          /* Given datatype name            */
  char                mapped[256];        /* Equivalent name                */
} SwigCacheType;

static int SwigPtrMax  = 64;           /* Max entries that can be currently held */
static int SwigPtrN    = 0;            /* Current number of entries              */
static int SwigPtrSort = 0;            /* Status flag indicating sort            */
static int SwigStart[256];             /* Starting positions of types            */
static SwigPtrType *SwigPtrTable = 0;  /* Table containing pointer equivalences  */

/* Cached values */
#define SWIG_CACHESIZE  8
#define SWIG_CACHEMASK  0x7
static SwigCacheType SwigCache[SWIG_CACHESIZE];  
static int SwigCacheIndex = 0;
static int SwigLastCache = 0;

/* Sort comparison function */
static int swigsort(const void *data1, const void *data2) {
	SwigPtrType *d1 = (SwigPtrType *) data1;
	SwigPtrType *d2 = (SwigPtrType *) data2;
	return strcmp(d1->name,d2->name);
}

/* Register a new datatype with the type-checker */
SWIGSTATICRUNTIME(void) 
SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *)) {
  int i;
  SwigPtrType *t = 0,*t1;

  /* Allocate the pointer table if necessary */
  if (!SwigPtrTable) {     
    SwigPtrTable = (SwigPtrType *) malloc(SwigPtrMax*sizeof(SwigPtrType));
  }

  /* Grow the table */
  if (SwigPtrN >= SwigPtrMax) {
    SwigPtrMax = 2*SwigPtrMax;
    SwigPtrTable = (SwigPtrType *) realloc((char *) SwigPtrTable,SwigPtrMax*sizeof(SwigPtrType));
  }
  for (i = 0; i < SwigPtrN; i++) {
    if (strcmp(SwigPtrTable[i].name,origtype) == 0) {
      t = &SwigPtrTable[i];
      break;
    }
  }
  if (!t) {
    t = &SwigPtrTable[SwigPtrN++];
    t->name = origtype;
    t->len = strlen(t->name);
    t->cast = 0;
    t->next = 0;
  }

  /* Check for existing entries */
  while (t->next) {
    if ((strcmp(t->name,newtype) == 0)) {
      if (cast) t->cast = cast;
      return;
    }
    t = t->next;
  }
  t1 = (SwigPtrType *) malloc(sizeof(SwigPtrType));
  t1->name = newtype;
  t1->len = strlen(t1->name);
  t1->cast = cast;
  t1->next = 0;            
  t->next = t1;           
  SwigPtrSort = 0;
}

/* Make a pointer value string */
SWIGSTATICRUNTIME(void) 
SWIG_MakePtr(char *c, const void *ptr, char *type) {
  static char hex[17] = "0123456789abcdef";
  unsigned long p, s;
  char result[24], *r; 
  r = result;
  p = (unsigned long) ptr;
  if (p > 0) {
    while (p > 0) {
      s = p & 0xf;
      *(r++) = hex[s];
      p = p >> 4;
    }
    *r = '_';
    while (r >= result)
      *(c++) = *(r--);
    strcpy (c, type);
  } else {
    strcpy (c, "NULL");
  }
}

/* Function for getting a pointer value */
SWIGSTATICRUNTIME(char *) 
SWIG_GetPtr(char *c, void **ptr, char *t)
{
  unsigned long p;
  char temp_type[256], *name;
  int  i, len, start, end;
  SwigPtrType *sp,*tp;
  SwigCacheType *cache;
  register int d;

  p = 0;
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) return (char *) 0;
    else return c;
  }
  c++;
  /* Extract hex value from pointer */
  while (d = *c) {
    if ((d >= '0') && (d <= '9'))
      p = (p << 4) + (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      p = (p << 4) + (d - ('a'-10));
    else
      break; 
    c++;
  }
  *ptr = (void *) p;
  if ((!t) || (strcmp(t,c)==0)) return (char *) 0;

  if (!SwigPtrSort) {
    qsort((void *) SwigPtrTable, SwigPtrN, sizeof(SwigPtrType), swigsort); 
    for (i = 0; i < 256; i++) SwigStart[i] = SwigPtrN;
    for (i = SwigPtrN-1; i >= 0; i--) SwigStart[(int) (SwigPtrTable[i].name[1])] = i;
    for (i = 255; i >= 1; i--) {
      if (SwigStart[i-1] > SwigStart[i])
	SwigStart[i-1] = SwigStart[i];
    }
    SwigPtrSort = 1;
    for (i = 0; i < SWIG_CACHESIZE; i++) SwigCache[i].stat = 0;
  }
  /* First check cache for matches.  Uses last cache value as starting point */
  cache = &SwigCache[SwigLastCache];
  for (i = 0; i < SWIG_CACHESIZE; i++) {
    if (cache->stat && (strcmp(t,cache->name) == 0) && (strcmp(c,cache->mapped) == 0)) {
      cache->stat++;
      if (cache->tp->cast) *ptr = (*(cache->tp->cast))(*ptr);
      return (char *) 0;
    }
    SwigLastCache = (SwigLastCache+1) & SWIG_CACHEMASK;
    if (!SwigLastCache) cache = SwigCache;
    else cache++;
  }
  /* Type mismatch.  Look through type-mapping table */
  start = SwigStart[(int) t[1]];
  end = SwigStart[(int) t[1]+1];
  sp = &SwigPtrTable[start];

  /* Try to find a match */
  while (start <= end) {
    if (strncmp(t,sp->name,sp->len) == 0) {
      name = sp->name;
      len = sp->len;
      tp = sp->next;
      /* Try to find entry for our given datatype */
      while(tp) {
	if (tp->len >= 255) {
	  return c;
	}
	strcpy(temp_type,tp->name);
	strncat(temp_type,t+len,255-tp->len);
	if (strcmp(c,temp_type) == 0) {
	  strcpy(SwigCache[SwigCacheIndex].mapped,c);
	  strcpy(SwigCache[SwigCacheIndex].name,t);
	  SwigCache[SwigCacheIndex].stat = 1;
	  SwigCache[SwigCacheIndex].tp = tp;
	  SwigCacheIndex = SwigCacheIndex & SWIG_CACHEMASK;
	  /* Get pointer value */
	  *ptr = (void *) p;
	  if (tp->cast) *ptr = (*(tp->cast))(*ptr);
	  return (char *) 0;
	}
	tp = tp->next;
      }
    }
    sp++;
    start++;
  }
  return c;
} 

/* New object-based GetPointer function. This uses the Python abstract
 * object interface to automatically dereference the 'this' attribute
 * of shadow objects. */

SWIGSTATICRUNTIME(char *)
SWIG_GetPtrObj(PyObject *obj, void **ptr, char *type) {
  PyObject *sobj = obj;
  char     *str;
  if (!PyString_Check(obj)) {
    sobj = PyObject_GetAttrString(obj,"this");
    if (!sobj) return "";
  }
  str = PyString_AsString(sobj);
  return SWIG_GetPtr(str,ptr,type);
}

#ifdef __cplusplus
}
#endif


#define SWIG_init    initsvmc

#define SWIG_name    "svmc"

#include "svm.h"

#define  SWIG_MemoryError    1
#define  SWIG_IOError        2
#define  SWIG_RuntimeError   3
#define  SWIG_IndexError     4
#define  SWIG_TypeError      5
#define  SWIG_DivisionByZero 6
#define  SWIG_OverflowError  7
#define  SWIG_SyntaxError    8
#define  SWIG_ValueError     9
#define  SWIG_SystemError   10
#define  SWIG_UnknownError  99

static void _SWIG_exception(int code, char *msg) {
  switch(code) {
  case SWIG_MemoryError:
    PyErr_SetString(PyExc_MemoryError,msg);
    break;
  case SWIG_IOError:
    PyErr_SetString(PyExc_IOError,msg);
    break;
  case SWIG_RuntimeError:
    PyErr_SetString(PyExc_RuntimeError,msg);
    break;
  case SWIG_IndexError:
    PyErr_SetString(PyExc_IndexError,msg);
    break;
  case SWIG_TypeError:
    PyErr_SetString(PyExc_TypeError,msg);
    break;
  case SWIG_DivisionByZero:
    PyErr_SetString(PyExc_ZeroDivisionError,msg);
    break;
  case SWIG_OverflowError:
    PyErr_SetString(PyExc_OverflowError,msg);
    break;
  case SWIG_SyntaxError:
    PyErr_SetString(PyExc_SyntaxError,msg);
    break;
  case SWIG_ValueError:
    PyErr_SetString(PyExc_ValueError,msg);
    break;
  case SWIG_SystemError:
    PyErr_SetString(PyExc_SystemError,msg);
    break;
  default:
    PyErr_SetString(PyExc_RuntimeError,msg);
    break;
  }
}

#define SWIG_exception(a,b) _SWIG_exception(a,b); return NULL

#include <limits.h>

/* Create a new integer array */

  static int *int_array(int size) {
#ifdef __cplusplus
    return new int[size];
#else
    return (int *) malloc(size*sizeof(int));
#endif
  }

  /* Destroy an integer array */

  static void int_destroy(int *array) {
    if (array) {
#ifdef __cplusplus
      delete array;
#else
      free(array);
#endif
    }
  }

  /* Return an element */

  static int int_get(int *array, int index) {
    if (array) {
      return array[index];
    } else {
      return INT_MIN;
    }
  }
   
  /* Set an element */
  
  static int int_set(int *array, int index, int value) {
    if (array) {
      return (array[index] = value);
    } else {
      return INT_MIN;
    }
  }


  #include <float.h>

  /* Create a new float array */

  static float *float_array(int size) {
#ifdef __cplusplus
    return new float[size];
#else
    return (float *) malloc(size*sizeof(float));
#endif
  }

  /* Destroy an array */

  static void float_destroy(float *array) {
    if (array) {
#ifdef __cplusplus
      delete array;
#else
      free(array);
#endif
    }
  }

  /* Return an element */

  static float float_get(float *array, int index) {
    if (array) {
      return array[index];
    } else {
      return FLT_MIN;
    }
  }
   
  /* Set an element */
  
  static float float_set(float *array, int index, float value) {
    if (array) {
      return (array[index] = value);
    } else {
      return FLT_MIN;
    }
  }

  /* Create a new double array */

  static double *double_array(int size) {
#ifdef __cplusplus
    return new double[size];
#else
    return (double *) malloc(size*sizeof(double));
#endif
  }

  /* Destroy an array */

  static void double_destroy(double *array) {
    if (array) {
#ifdef __cplusplus
      delete array;
#else
      free(array);
#endif
    }
  }

  /* Return an element */

  static double double_get(double *array, int index) {
    if (array) {
      return array[index];
    } else {
      return FLT_MIN;
    }
  }
   
  /* Set an element */
  
  static double double_set(double *array, int index, double value) {
    if (array) {
      return (array[index] = value);
    } else {
      return FLT_MIN;
    }
  }


/* Create character string arrays */

static char **string_array(int size) {
  char **a;
  int i;
#ifdef __cplusplus
  a = new char *[size];
#else
  a = (char **) malloc(size*sizeof(char *));
#endif
  for (i = 0; i < size; i++)
    a[i] = 0;
  return a;
}

/* Destroy a string array */

static void string_destroy(char **array) {
  int i = 0;
  if (array) {
      while (array[i]) {
#ifdef __cplusplus
            delete array[i];
#else
            free(array[i]);
#endif
            i++;
      }          	
#ifdef __cplusplus
     delete array;
#else
     free(array);
#endif
   }      
}

/* Get an element */

static char *string_get(char **array_string, int index) {
  if (array_string) 
    if (array_string[index]) return (array_string[index]);
    else return "";
  else 
    return "";
}

/* Set an element */

static char *string_set(char **array_string, int index, char * val) {
  if (array_string) {
    if (array_string[index]) {
#ifdef __cplusplus
	delete array_string[index];
#else
        free(array_string[index]);
#endif
    }	
    if (strlen(val) > 0) {
#ifdef __cplusplus
      array_string[index] = new char[strlen(val)+1];
#else
      array_string[index] = (char *) malloc(strlen(val)+1);
#endif
      strcpy(array_string[index],val);
      return array_string[index];
    } else {
      array_string[index] = 0;
      return val;
    }
  } else return val;
}


struct svm_node *svm_node_array(int size)
{
	return (struct svm_node *)malloc(sizeof(struct svm_node)*size);
}

void svm_node_array_set(struct svm_node *array, int i, int index, double value)
{
	array[i].index = index;
	array[i].value = value;
}

void svm_node_array_destroy(struct svm_node *array)
{
	free(array);
}

struct svm_node **svm_node_matrix(int size)
{
	return (struct svm_node **)malloc(sizeof(struct svm_node *)*size);	
}

void svm_node_matrix_set(struct svm_node **matrix, int i, struct svm_node* array)
{
	matrix[i] = array;
}

void svm_node_matrix_destroy(struct svm_node **matrix)
{
	free(matrix);
}

#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_svm_train(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_model * _result;
    struct svm_problem * _arg0;
    struct svm_parameter * _arg1;
    PyObject * _argo0 = 0;
    PyObject * _argo1 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"OO:svm_train",&_argo0,&_argo1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_problem_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_train. Expected _struct_svm_problem_p.");
        return NULL;
        }
    }
    if (_argo1) {
        if (_argo1 == Py_None) { _arg1 = NULL; }
        else if (SWIG_GetPtrObj(_argo1,(void **) &_arg1,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of svm_train. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (struct svm_model *)svm_train(_arg0,_arg1);
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_struct_svm_model_p");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
    return _resultobj;
}

static PyObject *_wrap_svm_save_model(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    char * _arg0;
    struct svm_model * _arg1;
    PyObject * _argo1 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sO:svm_save_model",&_arg0,&_argo1)) 
        return NULL;
    if (_argo1) {
        if (_argo1 == Py_None) { _arg1 = NULL; }
        else if (SWIG_GetPtrObj(_argo1,(void **) &_arg1,"_struct_svm_model_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of svm_save_model. Expected _struct_svm_model_p.");
        return NULL;
        }
    }
    _result = (int )svm_save_model(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_svm_load_model(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_model * _result;
    char * _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"s:svm_load_model",&_arg0)) 
        return NULL;
    _result = (struct svm_model *)svm_load_model(_arg0);
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_struct_svm_model_p");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
    return _resultobj;
}

static PyObject *_wrap_svm_predict(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_model * _arg0;
    struct svm_node * _arg1;
    PyObject * _argo0 = 0;
    PyObject * _argo1 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"OO:svm_predict",&_argo0,&_argo1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_model_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_predict. Expected _struct_svm_model_p.");
        return NULL;
        }
    }
    if (_argo1) {
        if (_argo1 == Py_None) { _arg1 = NULL; }
        else if (SWIG_GetPtrObj(_argo1,(void **) &_arg1,"_struct_svm_node_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of svm_predict. Expected _struct_svm_node_p.");
        return NULL;
        }
    }
    _result = (double )svm_predict(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

static PyObject *_wrap_svm_get_nr_class(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_model * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_get_nr_class",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_model_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_get_nr_class. Expected _struct_svm_model_p.");
        return NULL;
        }
    }
    _result = (int )svm_get_nr_class(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_svm_get_labels(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_model * _arg0;
    int * _arg1;
    PyObject * _argo0 = 0;
    PyObject * _argo1 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"OO:svm_get_labels",&_argo0,&_argo1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_model_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_get_labels. Expected _struct_svm_model_p.");
        return NULL;
        }
    }
    if (_argo1) {
        if (_argo1 == Py_None) { _arg1 = NULL; }
        else if (SWIG_GetPtrObj(_argo1,(void **) &_arg1,"_int_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of svm_get_labels. Expected _int_p.");
        return NULL;
        }
    }
    svm_get_labels(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_svm_predict_values(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_model * _arg0;
    struct svm_node * _arg1;
    double * _arg2;
    PyObject * _argo0 = 0;
    PyObject * _argo1 = 0;
    PyObject * _argo2 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"OOO:svm_predict_values",&_argo0,&_argo1,&_argo2)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_model_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_predict_values. Expected _struct_svm_model_p.");
        return NULL;
        }
    }
    if (_argo1) {
        if (_argo1 == Py_None) { _arg1 = NULL; }
        else if (SWIG_GetPtrObj(_argo1,(void **) &_arg1,"_struct_svm_node_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of svm_predict_values. Expected _struct_svm_node_p.");
        return NULL;
        }
    }
    if (_argo2) {
        if (_argo2 == Py_None) { _arg2 = NULL; }
        else if (SWIG_GetPtrObj(_argo2,(void **) &_arg2,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 3 of svm_predict_values. Expected _double_p.");
        return NULL;
        }
    }
    svm_predict_values(_arg0,_arg1,_arg2);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_svm_destroy_model(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_model * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_destroy_model",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_model_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_destroy_model. Expected _struct_svm_model_p.");
        return NULL;
        }
    }
    svm_destroy_model(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_svm_check_parameter(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char * _result;
    struct svm_problem * _arg0;
    struct svm_parameter * _arg1;
    PyObject * _argo0 = 0;
    PyObject * _argo1 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"OO:svm_check_parameter",&_argo0,&_argo1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_problem_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_check_parameter. Expected _struct_svm_problem_p.");
        return NULL;
        }
    }
    if (_argo1) {
        if (_argo1 == Py_None) { _arg1 = NULL; }
        else if (SWIG_GetPtrObj(_argo1,(void **) &_arg1,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of svm_check_parameter. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (char *)svm_check_parameter(_arg0,_arg1);
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

static PyObject *_wrap_int_array(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int * _result;
    int  _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"i:int_array",&_arg0)) 
        return NULL;
    _result = (int *)int_array(_arg0);
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_int_p");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
{
  if (!_result) {
    SWIG_exception(SWIG_MemoryError,"Out of memory.");
  }
}
    return _resultobj;
}

static PyObject *_wrap_int_destroy(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:int_destroy",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_int_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of int_destroy. Expected _int_p.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    int_destroy(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_int_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    int * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:int_get",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_int_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of int_get. Expected _int_p.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    _result = (int )int_get(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_int_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    int * _arg0;
    int  _arg1;
    int  _arg2;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oii:int_set",&_argo0,&_arg1,&_arg2)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_int_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of int_set. Expected _int_p.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    _result = (int )int_set(_arg0,_arg1,_arg2);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_double_array(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double * _result;
    int  _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"i:double_array",&_arg0)) 
        return NULL;
    _result = (double *)double_array(_arg0);
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_double_p");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
{
  if (!_result) {
    SWIG_exception(SWIG_MemoryError,"Out of memory.");
  }
}
    return _resultobj;
}

static PyObject *_wrap_double_destroy(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:double_destroy",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of double_destroy. Expected _double_p.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    double_destroy(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_double_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    double * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:double_get",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of double_get. Expected _double_p.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    _result = (double )double_get(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

static PyObject *_wrap_double_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    double * _arg0;
    int  _arg1;
    double  _arg2;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oid:double_set",&_argo0,&_arg1,&_arg2)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of double_set. Expected _double_p.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    _result = (double )double_set(_arg0,_arg1,_arg2);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

static PyObject *_wrap_float_array(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    float * _result;
    int  _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"i:float_array",&_arg0)) 
        return NULL;
    _result = (float *)float_array(_arg0);
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_float_p");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
{
  if (!_result) {
    SWIG_exception(SWIG_MemoryError,"Out of memory.");
  }
}
    return _resultobj;
}

static PyObject *_wrap_float_destroy(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    float * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:float_destroy",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_float_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of float_destroy. Expected _float_p.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    float_destroy(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_float_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    float  _result;
    float * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:float_get",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_float_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of float_get. Expected _float_p.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    _result = (float )float_get(_arg0,_arg1);
    _resultobj = Py_BuildValue("f",_result);
    return _resultobj;
}

static PyObject *_wrap_float_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    float  _result;
    float * _arg0;
    int  _arg1;
    float  _arg2;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oif:float_set",&_argo0,&_arg1,&_arg2)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_float_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of float_set. Expected _float_p.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    _result = (float )float_set(_arg0,_arg1,_arg2);
    _resultobj = Py_BuildValue("f",_result);
    return _resultobj;
}

static PyObject *_wrap_string_array(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char ** _result;
    int  _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"i:string_array",&_arg0)) 
        return NULL;
    _result = (char **)string_array(_arg0);
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_char_pp");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
{
  if (!_result) {
    SWIG_exception(SWIG_MemoryError,"Out of memory.");
  }
}
    return _resultobj;
}

static PyObject *_wrap_string_destroy(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char ** _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:string_destroy",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_char_pp")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of string_destroy. Expected _char_pp.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    string_destroy(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_string_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char * _result;
    char ** _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:string_get",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_char_pp")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of string_get. Expected _char_pp.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    _result = (char *)string_get(_arg0,_arg1);
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

static PyObject *_wrap_string_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char * _result;
    char ** _arg0;
    int  _arg1;
    char * _arg2;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Ois:string_set",&_argo0,&_arg1,&_arg2)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_char_pp")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of string_set. Expected _char_pp.");
        return NULL;
        }
    }
{
  if (!_arg0) {
    SWIG_exception(SWIG_ValueError,"Received a NULL Pointer");
  }
}
    _result = (char *)string_set(_arg0,_arg1,_arg2);
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

static PyObject *_wrap_svm_node_array(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_node * _result;
    int  _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"i:svm_node_array",&_arg0)) 
        return NULL;
    _result = (struct svm_node *)svm_node_array(_arg0);
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_struct_svm_node_p");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
    return _resultobj;
}

static PyObject *_wrap_svm_node_array_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_node * _arg0;
    int  _arg1;
    int  _arg2;
    double  _arg3;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oiid:svm_node_array_set",&_argo0,&_arg1,&_arg2,&_arg3)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_node_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_node_array_set. Expected _struct_svm_node_p.");
        return NULL;
        }
    }
    svm_node_array_set(_arg0,_arg1,_arg2,_arg3);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_svm_node_array_destroy(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_node * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_node_array_destroy",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_node_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_node_array_destroy. Expected _struct_svm_node_p.");
        return NULL;
        }
    }
    svm_node_array_destroy(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_svm_node_matrix(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_node ** _result;
    int  _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"i:svm_node_matrix",&_arg0)) 
        return NULL;
    _result = (struct svm_node **)svm_node_matrix(_arg0);
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_struct_svm_node_pp");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
    return _resultobj;
}

static PyObject *_wrap_svm_node_matrix_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_node ** _arg0;
    int  _arg1;
    struct svm_node * _arg2;
    PyObject * _argo0 = 0;
    PyObject * _argo2 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"OiO:svm_node_matrix_set",&_argo0,&_arg1,&_argo2)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_node_pp")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_node_matrix_set. Expected _struct_svm_node_pp.");
        return NULL;
        }
    }
    if (_argo2) {
        if (_argo2 == Py_None) { _arg2 = NULL; }
        else if (SWIG_GetPtrObj(_argo2,(void **) &_arg2,"_struct_svm_node_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 3 of svm_node_matrix_set. Expected _struct_svm_node_p.");
        return NULL;
        }
    }
    svm_node_matrix_set(_arg0,_arg1,_arg2);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_svm_node_matrix_destroy(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_node ** _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_node_matrix_destroy",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_node_pp")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_node_matrix_destroy. Expected _struct_svm_node_pp.");
        return NULL;
        }
    }
    svm_node_matrix_destroy(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define svm_parameter_svm_type_set(_swigobj,_swigval) (_swigobj->svm_type = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_svm_type_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_parameter * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:svm_parameter_svm_type_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_svm_type_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (int )svm_parameter_svm_type_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define svm_parameter_svm_type_get(_swigobj) ((int ) _swigobj->svm_type)
static PyObject *_wrap_svm_parameter_svm_type_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_parameter * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_parameter_svm_type_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_svm_type_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (int )svm_parameter_svm_type_get(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define svm_parameter_kernel_type_set(_swigobj,_swigval) (_swigobj->kernel_type = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_kernel_type_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_parameter * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:svm_parameter_kernel_type_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_kernel_type_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (int )svm_parameter_kernel_type_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define svm_parameter_kernel_type_get(_swigobj) ((int ) _swigobj->kernel_type)
static PyObject *_wrap_svm_parameter_kernel_type_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_parameter * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_parameter_kernel_type_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_kernel_type_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (int )svm_parameter_kernel_type_get(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define svm_parameter_degree_set(_swigobj,_swigval) (_swigobj->degree = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_degree_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    double  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Od:svm_parameter_degree_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_degree_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_degree_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_degree_get(_swigobj) ((double ) _swigobj->degree)
static PyObject *_wrap_svm_parameter_degree_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_parameter_degree_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_degree_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_degree_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_gamma_set(_swigobj,_swigval) (_swigobj->gamma = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_gamma_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    double  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Od:svm_parameter_gamma_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_gamma_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_gamma_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_gamma_get(_swigobj) ((double ) _swigobj->gamma)
static PyObject *_wrap_svm_parameter_gamma_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_parameter_gamma_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_gamma_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_gamma_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_coef0_set(_swigobj,_swigval) (_swigobj->coef0 = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_coef0_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    double  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Od:svm_parameter_coef0_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_coef0_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_coef0_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_coef0_get(_swigobj) ((double ) _swigobj->coef0)
static PyObject *_wrap_svm_parameter_coef0_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_parameter_coef0_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_coef0_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_coef0_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_cache_size_set(_swigobj,_swigval) (_swigobj->cache_size = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_cache_size_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    double  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Od:svm_parameter_cache_size_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_cache_size_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_cache_size_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_cache_size_get(_swigobj) ((double ) _swigobj->cache_size)
static PyObject *_wrap_svm_parameter_cache_size_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_parameter_cache_size_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_cache_size_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_cache_size_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_eps_set(_swigobj,_swigval) (_swigobj->eps = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_eps_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    double  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Od:svm_parameter_eps_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_eps_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_eps_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_eps_get(_swigobj) ((double ) _swigobj->eps)
static PyObject *_wrap_svm_parameter_eps_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_parameter_eps_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_eps_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_eps_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_C_set(_swigobj,_swigval) (_swigobj->C = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_C_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    double  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Od:svm_parameter_C_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_C_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_C_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_C_get(_swigobj) ((double ) _swigobj->C)
static PyObject *_wrap_svm_parameter_C_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_parameter_C_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_C_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_C_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_nr_weight_set(_swigobj,_swigval) (_swigobj->nr_weight = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_nr_weight_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_parameter * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:svm_parameter_nr_weight_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_nr_weight_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (int )svm_parameter_nr_weight_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define svm_parameter_nr_weight_get(_swigobj) ((int ) _swigobj->nr_weight)
static PyObject *_wrap_svm_parameter_nr_weight_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_parameter * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_parameter_nr_weight_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_nr_weight_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (int )svm_parameter_nr_weight_get(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define svm_parameter_weight_label_set(_swigobj,_swigval) (_swigobj->weight_label = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_weight_label_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int * _result;
    struct svm_parameter * _arg0;
    int * _arg1;
    PyObject * _argo0 = 0;
    PyObject * _argo1 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"OO:svm_parameter_weight_label_set",&_argo0,&_argo1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_weight_label_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    if (_argo1) {
        if (_argo1 == Py_None) { _arg1 = NULL; }
        else if (SWIG_GetPtrObj(_argo1,(void **) &_arg1,"_int_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of svm_parameter_weight_label_set. Expected _int_p.");
        return NULL;
        }
    }
    _result = (int *)svm_parameter_weight_label_set(_arg0,_arg1);
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_int_p");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
    return _resultobj;
}

#define svm_parameter_weight_label_get(_swigobj) ((int *) _swigobj->weight_label)
static PyObject *_wrap_svm_parameter_weight_label_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int * _result;
    struct svm_parameter * _arg0;
    PyObject * _argo0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_parameter_weight_label_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_weight_label_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (int *)svm_parameter_weight_label_get(_arg0);
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_int_p");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
    return _resultobj;
}

#define svm_parameter_weight_set(_swigobj,_swigval) (_swigobj->weight = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_weight_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double * _result;
    struct svm_parameter * _arg0;
    double * _arg1;
    PyObject * _argo0 = 0;
    PyObject * _argo1 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"OO:svm_parameter_weight_set",&_argo0,&_argo1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_weight_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    if (_argo1) {
        if (_argo1 == Py_None) { _arg1 = NULL; }
        else if (SWIG_GetPtrObj(_argo1,(void **) &_arg1,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of svm_parameter_weight_set. Expected _double_p.");
        return NULL;
        }
    }
    _result = (double *)svm_parameter_weight_set(_arg0,_arg1);
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_double_p");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
    return _resultobj;
}

#define svm_parameter_weight_get(_swigobj) ((double *) _swigobj->weight)
static PyObject *_wrap_svm_parameter_weight_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double * _result;
    struct svm_parameter * _arg0;
    PyObject * _argo0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_parameter_weight_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_weight_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double *)svm_parameter_weight_get(_arg0);
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_double_p");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
    return _resultobj;
}

#define svm_parameter_nu_set(_swigobj,_swigval) (_swigobj->nu = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_nu_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    double  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Od:svm_parameter_nu_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_nu_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_nu_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_nu_get(_swigobj) ((double ) _swigobj->nu)
static PyObject *_wrap_svm_parameter_nu_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_parameter_nu_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_nu_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_nu_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_p_set(_swigobj,_swigval) (_swigobj->p = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_p_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    double  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Od:svm_parameter_p_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_p_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_p_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_p_get(_swigobj) ((double ) _swigobj->p)
static PyObject *_wrap_svm_parameter_p_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    struct svm_parameter * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_parameter_p_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_p_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (double )svm_parameter_p_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define svm_parameter_shrinking_set(_swigobj,_swigval) (_swigobj->shrinking = _swigval,_swigval)
static PyObject *_wrap_svm_parameter_shrinking_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_parameter * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:svm_parameter_shrinking_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_shrinking_set. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (int )svm_parameter_shrinking_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define svm_parameter_shrinking_get(_swigobj) ((int ) _swigobj->shrinking)
static PyObject *_wrap_svm_parameter_shrinking_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_parameter * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_parameter_shrinking_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_parameter_shrinking_get. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    _result = (int )svm_parameter_shrinking_get(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define new_svm_parameter() ((struct svm_parameter *) calloc(1,sizeof(struct svm_parameter)))
static PyObject *_wrap_new_svm_parameter(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_parameter * _result;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,":new_svm_parameter")) 
        return NULL;
    _result = (struct svm_parameter *)new_svm_parameter();
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_struct_svm_parameter_p");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
    return _resultobj;
}

#define delete_svm_parameter(_swigobj) (free ((char *) _swigobj))
static PyObject *_wrap_delete_svm_parameter(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_parameter * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:delete_svm_parameter",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_parameter_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of delete_svm_parameter. Expected _struct_svm_parameter_p.");
        return NULL;
        }
    }
    delete_svm_parameter(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define svm_problem_l_set(_swigobj,_swigval) (_swigobj->l = _swigval,_swigval)
static PyObject *_wrap_svm_problem_l_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_problem * _arg0;
    int  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:svm_problem_l_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_problem_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_problem_l_set. Expected _struct_svm_problem_p.");
        return NULL;
        }
    }
    _result = (int )svm_problem_l_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define svm_problem_l_get(_swigobj) ((int ) _swigobj->l)
static PyObject *_wrap_svm_problem_l_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    struct svm_problem * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_problem_l_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_problem_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_problem_l_get. Expected _struct_svm_problem_p.");
        return NULL;
        }
    }
    _result = (int )svm_problem_l_get(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define svm_problem_y_set(_swigobj,_swigval) (_swigobj->y = _swigval,_swigval)
static PyObject *_wrap_svm_problem_y_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double * _result;
    struct svm_problem * _arg0;
    double * _arg1;
    PyObject * _argo0 = 0;
    PyObject * _argo1 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"OO:svm_problem_y_set",&_argo0,&_argo1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_problem_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_problem_y_set. Expected _struct_svm_problem_p.");
        return NULL;
        }
    }
    if (_argo1) {
        if (_argo1 == Py_None) { _arg1 = NULL; }
        else if (SWIG_GetPtrObj(_argo1,(void **) &_arg1,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of svm_problem_y_set. Expected _double_p.");
        return NULL;
        }
    }
    _result = (double *)svm_problem_y_set(_arg0,_arg1);
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_double_p");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
    return _resultobj;
}

#define svm_problem_y_get(_swigobj) ((double *) _swigobj->y)
static PyObject *_wrap_svm_problem_y_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double * _result;
    struct svm_problem * _arg0;
    PyObject * _argo0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_problem_y_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_problem_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_problem_y_get. Expected _struct_svm_problem_p.");
        return NULL;
        }
    }
    _result = (double *)svm_problem_y_get(_arg0);
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_double_p");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
    return _resultobj;
}

#define svm_problem_x_set(_swigobj,_swigval) (_swigobj->x = _swigval,_swigval)
static PyObject *_wrap_svm_problem_x_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_node ** _result;
    struct svm_problem * _arg0;
    struct svm_node ** _arg1;
    PyObject * _argo0 = 0;
    PyObject * _argo1 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"OO:svm_problem_x_set",&_argo0,&_argo1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_problem_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_problem_x_set. Expected _struct_svm_problem_p.");
        return NULL;
        }
    }
    if (_argo1) {
        if (_argo1 == Py_None) { _arg1 = NULL; }
        else if (SWIG_GetPtrObj(_argo1,(void **) &_arg1,"_struct_svm_node_pp")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of svm_problem_x_set. Expected _struct_svm_node_pp.");
        return NULL;
        }
    }
    _result = (struct svm_node **)svm_problem_x_set(_arg0,_arg1);
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_struct_svm_node_pp");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
    return _resultobj;
}

#define svm_problem_x_get(_swigobj) ((struct svm_node **) _swigobj->x)
static PyObject *_wrap_svm_problem_x_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_node ** _result;
    struct svm_problem * _arg0;
    PyObject * _argo0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"O:svm_problem_x_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_problem_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of svm_problem_x_get. Expected _struct_svm_problem_p.");
        return NULL;
        }
    }
    _result = (struct svm_node **)svm_problem_x_get(_arg0);
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_struct_svm_node_pp");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
    return _resultobj;
}

#define new_svm_problem() ((struct svm_problem *) calloc(1,sizeof(struct svm_problem)))
static PyObject *_wrap_new_svm_problem(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_problem * _result;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,":new_svm_problem")) 
        return NULL;
    _result = (struct svm_problem *)new_svm_problem();
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_struct_svm_problem_p");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
    return _resultobj;
}

#define delete_svm_problem(_swigobj) (free ((char *) _swigobj))
static PyObject *_wrap_delete_svm_problem(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct svm_problem * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:delete_svm_problem",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_svm_problem_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of delete_svm_problem. Expected _struct_svm_problem_p.");
        return NULL;
        }
    }
    delete_svm_problem(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyMethodDef svmcMethods[] = {
	 { "delete_svm_problem", _wrap_delete_svm_problem, METH_VARARGS },
	 { "new_svm_problem", _wrap_new_svm_problem, METH_VARARGS },
	 { "svm_problem_x_get", _wrap_svm_problem_x_get, METH_VARARGS },
	 { "svm_problem_x_set", _wrap_svm_problem_x_set, METH_VARARGS },
	 { "svm_problem_y_get", _wrap_svm_problem_y_get, METH_VARARGS },
	 { "svm_problem_y_set", _wrap_svm_problem_y_set, METH_VARARGS },
	 { "svm_problem_l_get", _wrap_svm_problem_l_get, METH_VARARGS },
	 { "svm_problem_l_set", _wrap_svm_problem_l_set, METH_VARARGS },
	 { "delete_svm_parameter", _wrap_delete_svm_parameter, METH_VARARGS },
	 { "new_svm_parameter", _wrap_new_svm_parameter, METH_VARARGS },
	 { "svm_parameter_shrinking_get", _wrap_svm_parameter_shrinking_get, METH_VARARGS },
	 { "svm_parameter_shrinking_set", _wrap_svm_parameter_shrinking_set, METH_VARARGS },
	 { "svm_parameter_p_get", _wrap_svm_parameter_p_get, METH_VARARGS },
	 { "svm_parameter_p_set", _wrap_svm_parameter_p_set, METH_VARARGS },
	 { "svm_parameter_nu_get", _wrap_svm_parameter_nu_get, METH_VARARGS },
	 { "svm_parameter_nu_set", _wrap_svm_parameter_nu_set, METH_VARARGS },
	 { "svm_parameter_weight_get", _wrap_svm_parameter_weight_get, METH_VARARGS },
	 { "svm_parameter_weight_set", _wrap_svm_parameter_weight_set, METH_VARARGS },
	 { "svm_parameter_weight_label_get", _wrap_svm_parameter_weight_label_get, METH_VARARGS },
	 { "svm_parameter_weight_label_set", _wrap_svm_parameter_weight_label_set, METH_VARARGS },
	 { "svm_parameter_nr_weight_get", _wrap_svm_parameter_nr_weight_get, METH_VARARGS },
	 { "svm_parameter_nr_weight_set", _wrap_svm_parameter_nr_weight_set, METH_VARARGS },
	 { "svm_parameter_C_get", _wrap_svm_parameter_C_get, METH_VARARGS },
	 { "svm_parameter_C_set", _wrap_svm_parameter_C_set, METH_VARARGS },
	 { "svm_parameter_eps_get", _wrap_svm_parameter_eps_get, METH_VARARGS },
	 { "svm_parameter_eps_set", _wrap_svm_parameter_eps_set, METH_VARARGS },
	 { "svm_parameter_cache_size_get", _wrap_svm_parameter_cache_size_get, METH_VARARGS },
	 { "svm_parameter_cache_size_set", _wrap_svm_parameter_cache_size_set, METH_VARARGS },
	 { "svm_parameter_coef0_get", _wrap_svm_parameter_coef0_get, METH_VARARGS },
	 { "svm_parameter_coef0_set", _wrap_svm_parameter_coef0_set, METH_VARARGS },
	 { "svm_parameter_gamma_get", _wrap_svm_parameter_gamma_get, METH_VARARGS },
	 { "svm_parameter_gamma_set", _wrap_svm_parameter_gamma_set, METH_VARARGS },
	 { "svm_parameter_degree_get", _wrap_svm_parameter_degree_get, METH_VARARGS },
	 { "svm_parameter_degree_set", _wrap_svm_parameter_degree_set, METH_VARARGS },
	 { "svm_parameter_kernel_type_get", _wrap_svm_parameter_kernel_type_get, METH_VARARGS },
	 { "svm_parameter_kernel_type_set", _wrap_svm_parameter_kernel_type_set, METH_VARARGS },
	 { "svm_parameter_svm_type_get", _wrap_svm_parameter_svm_type_get, METH_VARARGS },
	 { "svm_parameter_svm_type_set", _wrap_svm_parameter_svm_type_set, METH_VARARGS },
	 { "svm_node_matrix_destroy", _wrap_svm_node_matrix_destroy, METH_VARARGS },
	 { "svm_node_matrix_set", _wrap_svm_node_matrix_set, METH_VARARGS },
	 { "svm_node_matrix", _wrap_svm_node_matrix, METH_VARARGS },
	 { "svm_node_array_destroy", _wrap_svm_node_array_destroy, METH_VARARGS },
	 { "svm_node_array_set", _wrap_svm_node_array_set, METH_VARARGS },
	 { "svm_node_array", _wrap_svm_node_array, METH_VARARGS },
	 { "string_set", _wrap_string_set, METH_VARARGS },
	 { "string_get", _wrap_string_get, METH_VARARGS },
	 { "string_destroy", _wrap_string_destroy, METH_VARARGS },
	 { "string_array", _wrap_string_array, METH_VARARGS },
	 { "float_set", _wrap_float_set, METH_VARARGS },
	 { "float_get", _wrap_float_get, METH_VARARGS },
	 { "float_destroy", _wrap_float_destroy, METH_VARARGS },
	 { "float_array", _wrap_float_array, METH_VARARGS },
	 { "double_set", _wrap_double_set, METH_VARARGS },
	 { "double_get", _wrap_double_get, METH_VARARGS },
	 { "double_destroy", _wrap_double_destroy, METH_VARARGS },
	 { "double_array", _wrap_double_array, METH_VARARGS },
	 { "int_set", _wrap_int_set, METH_VARARGS },
	 { "int_get", _wrap_int_get, METH_VARARGS },
	 { "int_destroy", _wrap_int_destroy, METH_VARARGS },
	 { "int_array", _wrap_int_array, METH_VARARGS },
	 { "svm_check_parameter", _wrap_svm_check_parameter, METH_VARARGS },
	 { "svm_destroy_model", _wrap_svm_destroy_model, METH_VARARGS },
	 { "svm_predict_values", _wrap_svm_predict_values, METH_VARARGS },
	 { "svm_get_labels", _wrap_svm_get_labels, METH_VARARGS },
	 { "svm_get_nr_class", _wrap_svm_get_nr_class, METH_VARARGS },
	 { "svm_predict", _wrap_svm_predict, METH_VARARGS },
	 { "svm_load_model", _wrap_svm_load_model, METH_VARARGS },
	 { "svm_save_model", _wrap_svm_save_model, METH_VARARGS },
	 { "svm_train", _wrap_svm_train, METH_VARARGS },
	 { NULL, NULL }
};
#ifdef __cplusplus
}
#endif
/*
 * This table is used by the pointer type-checker
 */
static struct { char *n1; char *n2; void *(*pcnv)(void *); } _swig_mapping[] = {
    { "_signed_long","_long",0},
    { "_long","_unsigned_long",0},
    { "_long","_signed_long",0},
    { "_svm_problem","_struct_svm_problem",0},
    { "_unsigned_long","_long",0},
    { "_signed_int","_int",0},
    { "_svm_parameter","_struct_svm_parameter",0},
    { "_unsigned_short","_short",0},
    { "_signed_short","_short",0},
    { "_unsigned_int","_int",0},
    { "_short","_unsigned_short",0},
    { "_short","_signed_short",0},
    { "_int","_unsigned_int",0},
    { "_int","_signed_int",0},
    { "_struct_svm_problem","_svm_problem",0},
    { "_struct_svm_parameter","_svm_parameter",0},
{0,0,0}};

static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT(void) initsvmc() {
	 PyObject *m, *d;
	 SWIG_globals = SWIG_newvarlink();
	 m = Py_InitModule("svmc", svmcMethods);
	 d = PyModule_GetDict(m);
	 PyDict_SetItemString(d,"C_SVC", PyInt_FromLong((long) C_SVC));
	 PyDict_SetItemString(d,"NU_SVC", PyInt_FromLong((long) NU_SVC));
	 PyDict_SetItemString(d,"ONE_CLASS", PyInt_FromLong((long) ONE_CLASS));
	 PyDict_SetItemString(d,"EPSILON_SVR", PyInt_FromLong((long) EPSILON_SVR));
	 PyDict_SetItemString(d,"NU_SVR", PyInt_FromLong((long) NU_SVR));
	 PyDict_SetItemString(d,"LINEAR", PyInt_FromLong((long) LINEAR));
	 PyDict_SetItemString(d,"POLY", PyInt_FromLong((long) POLY));
	 PyDict_SetItemString(d,"RBF", PyInt_FromLong((long) RBF));
	 PyDict_SetItemString(d,"SIGMOID", PyInt_FromLong((long) SIGMOID));
{
   int i;
   for (i = 0; _swig_mapping[i].n1; i++)
        SWIG_RegisterMapping(_swig_mapping[i].n1,_swig_mapping[i].n2,_swig_mapping[i].pcnv);
}
}
